<?php
// Generates an additive import only; never connects to a database.
$out = "-- Expanded field-service reference library. Review drafts before publication.\nSET NAMES utf8mb4;\nSTART TRANSACTION;\nSET @author_id = (SELECT u.id FROM users u JOIN roles r ON r.id=u.role_id WHERE u.status='active' AND u.deleted_at IS NULL AND r.name IN ('Admin','Super Admin') ORDER BY u.id LIMIT 1);\n";
$counts = [];
function literal($value) {
    if ($value === null) return 'NULL';
    if (is_int($value)) return (string)$value;
    if (strpos($value, '\\') !== false) return "CONVERT(0x".bin2hex($value)." USING utf8mb4)";
    return "'".str_replace("'", "''", $value)."'";
}
function addRow($table, $data, $key, $from = '', $condition = '') {
    global $out, $counts;
    $values = array_map('literal', array_values($data));
    if ($table === 'knowledge_articles') $values[array_search('author_id', array_keys($data))] = '@author_id';
    if ($table === 'commands') $values[0] = 'c.id';
    $where = "NOT EXISTS (SELECT 1 FROM `$table` WHERE `$key`=".literal($data[$key]).")";
    if ($condition) $where = $condition.' AND '.$where;
    $out .= "\nINSERT INTO `$table` (`".implode('`,`', array_keys($data))."`)\nSELECT ".implode(',', $values).($from ? ' FROM '.$from : '')." WHERE $where;\n";
    $counts[$table] = ($counts[$table] ?? 0) + 1;
}
$ms = 'https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands';
$lenovo = 'https://support.lenovo.com/us/en/solutions/ht506581-lenovo-diagnostic-solutions-downloads';
$guides = [
 ['Laptop does not charge','Hardware','laptop','Battery percentage does not increase on AC','Distinguish:Record whether AC is detected, whether charging is intentionally limited and whether behavior changes with temperature.','Supply:Test an approved compatible charger directly without the dock; inspect the external connector for damage.','Diagnostics:Run supported battery and adapter tests; record battery health and failure IDs.','Repair:Follow the exact model manual for authorized battery or charging-path replacement. Stop use for swelling or unsafe heat.'],
 ['Laptop short battery runtime','Hardware','laptop','Battery drains faster than expected','Baseline:Record workload, brightness, battery age and actual runtime; compare only under comparable conditions.','Isolation:Compare idle and normal-workload behavior; review high CPU and background activity.','Evidence:Collect a battery report and manufacturer battery diagnostics; capacity estimates alone are not a complete fault diagnosis.','Resolution:Correct excess load or replace a confirmed degraded battery under the approved model procedure.'],
 ['Overheating and thermal throttling','Hardware','all','Reduced performance or shutdown under load','Scope:Record ambient conditions, workload and whether the fault occurs on AC or battery.','Airflow:Inspect unobstructed external vents; use a stable hard surface and check fan activity.','Isolation:Run approved thermal and fan diagnostics; compare temperatures against model guidance, not a universal threshold.','Service:Power-isolate before approved cleaning or fan replacement; follow model instructions for thermal materials. Stop if unsafe heat is present.'],
 ['Intermittent memory errors','Hardware','all','Crashes, POST failures or diagnostic memory errors','Evidence:Record error codes and whether crashes follow a memory upgrade.','Compatibility:Verify supported memory type, configuration and firmware using the exact machine type.','Isolation:Run extended manufacturer memory tests; authorized technicians may test supported modules and slots one at a time following the manual.','Validation:Retest each changed configuration and document the isolated faulty module or slot before replacing a FRU.'],
 ['Storage not detected in firmware','Hardware','all','Drive absent from firmware or diagnostics','Protect data:Ask whether recovery is required before changes; do not initialize or format the drive.','Configuration:Record firmware storage settings and recent changes without blindly switching controller modes.','Isolation:Use model diagnostics and approved connector inspection after power isolation.','Next action:If detection remains absent, arrange authorized drive or connector assessment; preserve the original drive for approved recovery.'],
 ['Slow storage or recurring disk errors','Hardware','all','Slow file access, I/O errors or drive warnings','Protect data:Back up readable critical data first; minimize testing if hardware failure is suspected.','Evidence:Record disk-related events, free space and manufacturer storage diagnostics.','Distinguish:Compare drive health, workload and file-system evidence; a health status of OK does not rule out every failure.','Resolution:Replace a confirmed failing drive under approved recovery procedures; use file-system repair only when evidence and backup justify it.'],
 ['Windows boot failure after change','Software','all','Windows fails after a driver, update or hardware change','Record:Capture exact error and the most recent change; distinguish firmware detection from Windows startup.','Protect access:Confirm backup and encryption recovery-key availability before recovery actions.','Isolate:Use approved Windows recovery or rollback appropriate to the specific change; avoid indiscriminate firmware resets.','Validate:Retest boot and workload; escalate with recovery logs if the next approved action risks data loss.'],
 ['Blue screen evidence collection','Software','all','Windows stop error or recurrent crash','Capture:Record stop code, timestamp, workload and recently changed drivers or hardware.','Collect:Save permitted crash dump and System events while protecting sensitive content.','Isolate:Correlate diagnostics, drivers and reproducible workload; a stop code alone does not prove a particular FRU is faulty.','Next action:Use approved driver rollback or manufacturer component tests, changing one variable at a time.'],
 ['USB-C dock has no external display','Hardware','laptop','Dock connected but external monitor blank','Compatibility:Confirm dock, host port, cable and display support the required video capability.','Direct test:Connect the display directly to a supported host output to isolate the dock path.','Power and input:Check dock supply, display input and a known-good compatible video cable.','Software:Apply model-approved dock firmware and drivers under stable power; retest each output separately.'],
 ['USB peripheral not detected','Hardware','all','USB device absent or intermittently disconnects','Scope:Determine whether one peripheral, one port or all ports are affected.','Cross-test:Use a known-good peripheral and supported alternate port; test the suspect device on another approved machine.','Evidence:Inspect Device Manager status and relevant events without uninstalling unrelated devices.','Repair:Isolate cable, peripheral or port fault; avoid forcing a damaged connector and use model-approved port servicing.'],
 ['Keyboard keys do not respond','Hardware','laptop','Some keys or entire keyboard fail','Scope:Check layout, accessibility settings and whether the failure occurs outside the affected application.','Cross-test:Try a known-good external keyboard and model-supported preboot keyboard test.','Inspect:Record liquid damage or physical obstruction; do not continue powering a liquid-damaged unit.','Service:Follow the model manual for approved keyboard or connector repair and verify every affected key.'],
 ['Touchpad unavailable','Hardware','laptop','Pointer works on external mouse but touchpad does not','Settings:Check supported touchpad enable controls and OS settings.','Evidence:Record Device Manager state and model-specific driver version.','Isolation:Compare behavior with approved preboot diagnostics or a supported clean driver state.','Service:If isolated to hardware, power-isolate and follow the exact touchpad/cable service procedure.'],
 ['Camera or microphone unavailable','Software','all','Application cannot use camera or microphone','Scope:Compare an approved alternate application and record whether only one program is affected.','Privacy:Check physical privacy controls and OS/application permissions; do not bypass organization policy.','Evidence:Confirm correct input device and inspect device/driver status.','Isolation:Test a known-good approved external device to distinguish application, driver and integrated-device faults.'],
 ['Ethernet link unavailable','Network','all','No wired link or adapter reports disconnected','Physical:Check cable connection and link indicators; test a known-good cable and approved switch port.','Adapter:Record adapter state with Get-NetAdapter and inspect driver/device status.','Network:Ask the network team to verify switch-port configuration and VLAN; do not make unauthorized changes.','Verify:Retest link, address and target service separately; log which stage fails.'],
 ['DHCP address unavailable','Network','all','No usable DHCP address or self-assigned address','Baseline:Record ipconfig /all and confirm whether the interface is intended to use DHCP.','Physical:Verify link and the correct network before renewing anything.','Service:Ask the network team to check DHCP scope, VLAN, relay and lease evidence.','Retest:Perform approved lease renewal only when disruption is acceptable; verify gateway, DNS and target service.'],
 ['Name resolution failure','Network','all','Service works by address but not hostname','Scope:Compare the exact hostname and an approved known-working name; record full error messages.','Configuration:Record assigned DNS servers and suffixes with ipconfig /all.','Evidence:Use Resolve-DnsName or nslookup against the intended resolver; compare internal versus external scope.','Next action:Correct authorized DNS configuration or ask the DNS owner to review records; do not replace enterprise DNS with a public resolver blindly.'],
 ['Wi-Fi intermittent disconnects','Network','laptop','Wireless connection drops during work','Scope:Record SSID, location, timing, signal context and whether other users are affected.','Compare:Test approved wired connectivity and another permitted access point if available.','Evidence:Collect wireless connection and driver events; correlate roam, sleep and workload changes.','Next action:Apply approved adapter updates or involve the wireless team with timestamps; do not disable required security settings.'],
 ['VPN connects but service unavailable','Network','all','VPN session active but internal service unreachable','Scope:Record target hostname, port and whether other approved services work.','Evidence:Compare DNS resolution and routing before and after VPN connection.','Service test:Use an approved TCP test against the exact internal service endpoint.','Escalate:Send route, DNS and service-test evidence to the VPN/network owner; do not disable firewall or change split-tunnel policy without approval.'],
 ['Printer queue stuck','Printer','printer','Jobs remain queued or fail repeatedly','Scope:Check whether one job, one user or all users are affected; record printer status and connectivity.','Device test:Run the printer built-in test page to distinguish print-engine issues from client jobs.','Queue evidence:Inspect the specific queue and job status using approved tools.','Recovery:Cancel only authorized affected jobs; restart shared spooler services only with approval because other users may be disrupted.'],
 ['Printer poor output quality','Printer','printer','Streaks, fading or repeated marks','Baseline:Print a built-in quality page and record which colors or areas are affected.','Consumables:Check correct supported toner/ink and supplies without substituting incompatible parts.','Maintenance:Run the manufacturer-approved calibration or cleaning cycle for the exact model.','Service:Use model-specific consumable or maintenance-unit replacement; allow hot components to cool and do not bypass safety covers.'],
 ['Display flicker or intermittent signal','Hardware','monitor','Image flickers or drops intermittently','Scope:Record refresh rate, resolution, dock path and workload.','Direct isolation:Bypass adapters/dock with a supported direct connection where possible.','Cross-test:Compare a known-good cable, display and source one at a time.','Resolution:Use supported display settings and approved graphics updates; replace only the isolated defective component.'],
 ['BitLocker recovery prompt after change','Security','all','Device requests recovery key','Protect information:Obtain recovery material only through the authorized organization process; never paste keys into public chat or reports.','Context:Record recent firmware, TPM, boot-order or hardware changes.','Recovery:Use the approved recovery process after identity and device ownership checks.','Prevent recurrence:Ask the endpoint owner to review the triggering change; do not clear TPM or disable encryption as a generic fix.'],
 ['Suspicious endpoint activity','Security','all','Possible malware or unauthorized activity','Preserve:Record observed indicators and notify the security team; do not delete evidence blindly.','Contain:Follow the organization isolation procedure rather than improvising security changes.','Protect:Avoid copying suspicious executables or confidential logs into chat.','Handover:Provide approved evidence, timestamps and actions taken; security approval governs restoration.'],
 ['Firmware update preflight','Hardware','all','Approved BIOS or device firmware maintenance','Identify:Verify exact machine type, applicable release and manufacturer instructions.','Protect:Confirm backup, encryption recovery-key handling and organization authorization.','Stability:Use approved stable power and satisfy battery or other model prerequisites.','Execute:Follow manufacturer update steps without interruption; capture versions and verify operation afterward. Do not flash firmware on unstable hardware.'],
];
foreach ($guides as $g) {
    [$title,$category,$device,$symptoms] = $g;
    $source = in_array($category,['Hardware'],true) ? $lenovo : $ms;
    addRow('knowledge_articles', ['title'=>'Field library: '.$title,'category'=>$category,'issue'=>$symptoms,'symptoms'=>$symptoms,'root_cause'=>'Requires diagnosis; do not infer a faulty part from the symptom alone.','solution'=>implode("\n",array_slice($g,4))."\nReference:".$source,'device_type'=>$device,'author_id'=>0,'status'=>'draft'], 'title', '', '@author_id IS NOT NULL');
}
$templates = [
 ['Service intake','Identification:Record real ticket, device model and serial, contact and location.','Symptom:Record exact behavior and customer impact without assuming root cause.','Consent:Record authorization, data protection and access restrictions.','Baseline:Record indicators and existing damage before service.'],
 ['Diagnostic test record','Test:Record test name, tool version, applicable device and start/end times.','Conditions:Record supply, connected peripherals and reproduction workload.','Result:Record exact code, outcome and saved evidence location.','Next action:Explain what the result rules in or out and the next untried test.'],
 ['Parts replacement record','Part:Record verified FRU and authorization; never invent part identifiers.','Evidence:Record diagnosis supporting replacement and prior failed checks.','Action taken:Record actual removal/replacement under the applicable manual.','Validation:Record post-repair test results and disposition of the old part.'],
 ['Network escalation handover','Scope:Record affected users, site, interface, service and timestamps.','Evidence:Record link state, address, gateway, DNS and service tests.','Changes:List approved changes and outcomes, including failed attempts.','Owner:Identify the responsible team and next action without exposing passwords.'],
 ['Device deployment acceptance','Asset:Record actual machine type, serial and assigned recipient.','Configuration:Record approved image, management enrollment and required applications.','Validation:Verify authorized network, peripherals, updates and encryption status.','Acceptance:Record recipient confirmation and unresolved items without publishing recovery keys.'],
 ['Preventive maintenance record','Authorization:Record maintenance scope and approved service window.','Baseline:Record health and existing faults before intervention.','Work:List only performed inspection, cleaning and approved updates.','Validation:Record post-maintenance diagnostics and any corrective actions needed.'],
 ['Return to service checklist','Original issue:Reproduce the original symptom and confirm its current state.','Diagnostics:Record relevant post-repair tests and their actual outcomes.','Configuration:Confirm supported settings and required management/security controls.','Closure:Record confirmation, remaining risks and whether the ticket is solved or unresolved.'],
 ['Unresolved troubleshooting handover','Symptom:Record exact persistent fault and reproduction conditions.','Action taken:List each completed check and outcome, especially failed checks.','Evidence:Reference logs and diagnostic codes without including credentials.','Next step:Record the next untried diagnostic, responsible team and authorization needed.'],
];
foreach ($templates as $t) addRow('knowledge_articles',['title'=>'Service documentation: '.$t[0],'category'=>'Software','issue'=>'Internal service documentation template; not a completed service record.','solution'=>implode("\n",array_slice($t,1)),'device_type'=>'all','author_id'=>0,'status'=>'draft'],'title','','@author_id IS NOT NULL');
$commands = [
 ['network','ipconfig /all','Display detailed interface addressing and DNS configuration.','Before changing IP or DNS settings.','ipconfig /all','Addresses, DHCP state, gateway and DNS servers.','safe',0],
 ['network','ipconfig /displaydns','Inspect cached DNS records.','Compare cached results with intended name resolution.','ipconfig /displaydns','Cached entries; absence alone does not prove a DNS fault.','safe',0],
 ['network','ipconfig /flushdns','Clear the local DNS resolver cache.','Only after documenting evidence of a stale local cache.','ipconfig /flushdns','Cache flush status; does not fix upstream DNS.','caution',0],
 ['network','ping','Test ICMP reachability to an approved endpoint.','Basic connectivity comparison.','ping gateway.example','Replies or timeouts; ICMP blocking does not prove the service is down.','safe',0],
 ['network','tracert','Inspect route hops toward an approved destination.','Compare route paths during a connectivity investigation.','tracert server.example','Hop responses; unresponsive hops may filter ICMP.','safe',0],
 ['network','nslookup','Query DNS information.','Investigate exact hostname resolution.','nslookup server.example','Resolver and query response.','safe',0],
 ['network','Resolve-DnsName','Query DNS records through PowerShell.','Inspect the intended hostname and record type.','Resolve-DnsName server.example','DNS records or a specific query error.','safe',1],
 ['network','Get-NetIPConfiguration','Display interface address, gateway and DNS details.','Baseline collection before network changes.','Get-NetIPConfiguration','Configuration per interface.','safe',1],
 ['network','Get-NetRoute','Inspect the routing table.','Compare routes when VPN or internal service access fails.','Get-NetRoute','Destination prefixes, interfaces and next hops.','safe',1],
 ['network','netstat -ano','Display connections with process identifiers.','Correlate a local application with network activity.','netstat -ano','Connection state and PID; protect host/address information.','safe',0],
 ['system','systeminfo','Display OS and system configuration.','Collect a baseline for support.','systeminfo','OS, boot and hardware summary.','safe',0],
 ['system','Get-WinEvent','Read event records with targeted filters.','Collect recent System evidence around a failure.','Get-WinEvent -FilterHashtable @{LogName="System"} -MaxEvents 30','Recent events; some logs require elevation.','safe',1],
 ['system','Get-Process','Inspect running processes.','Identify sustained workload before terminating anything.','Get-Process | Sort-Object CPU -Descending | Select-Object -First 10','Process identifiers and cumulative CPU time, not instantaneous CPU percentage.','safe',1],
 ['system','Get-Service','Read service status.','Check the affected application service without changing it.','Get-Service','Names and states; stopped may be normal for demand-start services.','safe',1],
 ['system','Get-CimInstance Win32_ComputerSystem','Read computer manufacturer and model.','Confirm machine identity before selecting manufacturer guidance.','Get-CimInstance Win32_ComputerSystem | Select-Object Manufacturer,Model','Reported model and manufacturer; still verify machine type.','safe',1],
 ['system','Get-CimInstance Win32_BIOS','Read BIOS version and reported serial.','Collect firmware and asset baseline.','Get-CimInstance Win32_BIOS | Select-Object SerialNumber,SMBIOSBIOSVersion','Reported identifiers; treat serials as organizational data.','safe',1],
 ['system','powercfg /batteryreport','Generate a battery usage and capacity report.','Investigate short runtime or capacity decline.','powercfg /batteryreport','Report location; capacity estimates require diagnostic context.','safe',0],
 ['system','powercfg /lastwake','Read the recorded last wake source.','Investigate unexpected wake rather than power loss.','powercfg /lastwake','Last recorded wake details, if available.','safe',0],
 ['disk','Get-Volume','Read volume capacity and file-system details.','Investigate low space without deleting data.','Get-Volume','Drive letters, file systems and capacity.','safe',1],
 ['disk','Get-Disk','Read disk identity and operational state.','Confirm which disk is affected before any storage action.','Get-Disk','Disk numbers, size and state; do not initialize an unknown disk.','safe',1],
 ['disk','Get-PhysicalDisk','Read storage-provider disk health information.','Gather health evidence alongside manufacturer diagnostics.','Get-PhysicalDisk','Provider-dependent health status; OK is not conclusive.','safe',1],
 ['disk','chkdsk','Inspect file-system status without requested repair.','Use after backup and when a file-system check is appropriate.','chkdsk C:','File-system report; active volumes can affect observations.','caution',0],
 ['printer','Get-Printer','List installed printer queues.','Identify the exact affected queue.','Get-Printer','Queue and driver information; PrintManagement module required.','safe',1],
 ['printer','Get-PrintJob','Read jobs in a specific printer queue.','Investigate a stuck job without clearing unrelated work.','Get-PrintJob -PrinterName "Office Printer"','Jobs for the named queue; module and permissions required.','safe',1],
];
foreach ($commands as $c) {
    [$slug,$command,$description,$when,$example,$expected,$risk,$ps] = $c;
    $url=$ms;
    if ($ps) {
        $module = in_array($command,['Get-WinEvent'],true) ? 'microsoft.powershell.diagnostics' : (in_array($command,['Get-Process','Get-Service'],true) ? 'microsoft.powershell.management' : null);
        if (!$module && in_array($command,['Get-NetIPConfiguration','Get-NetRoute'],true)) $module='nettcpip';
        if (!$module && $command==='Resolve-DnsName') $module='dnsclient';
        if (!$module && in_array($command,['Get-Volume','Get-Disk','Get-PhysicalDisk'],true)) $module='storage';
        if (!$module && in_array($command,['Get-Printer','Get-PrintJob'],true)) $module='printmanagement';
        if (!$module && strpos($command,'Get-CimInstance')===0) $module='cimcmdlets';
        if ($module) $url='https://learn.microsoft.com/en-us/powershell/module/'.$module.'/'.strtolower(explode(' ',$command)[0]);
    }
    addRow('commands',['category_id'=>0,'command'=>$command,'description'=>$description,'when_to_use'=>$when,'example'=>$example,'expected_output'=>$expected,'common_errors'=>'Check elevation, module availability, exact target and OS support. Do not infer hardware failure from one unsuccessful command.','next_steps'=>'Save relevant output with sensitive details redacted, then follow the next evidence-based diagnostic. Reference: '.$url,'risk_level'=>$risk,'is_powershell'=>$ps],'command','command_categories c',"c.slug=".literal($slug));
}
$tools = [
 ['Digital multimeter - authorized low-voltage use','gauge','Check supported low-voltage power measurements.','Only when the model procedure specifies permitted measurements.','Use approved ranges and leads according to the service procedure.','Never probe mains or open PSU/adaptor enclosures; this reference does not authorize live electrical work.'],
 ['Precision screwdriver and bit kit','wrench','Remove model-approved service fasteners.','Authorized internal service.','Match the documented bit and track screw positions; follow specified torque guidance.','Power-isolate; avoid stripping screws or damaging batteries.'],
 ['Nonconductive service opening tools','wrench','Release supported case clips during authorized service.','Only where the exact maintenance manual permits opening.','Follow clip sequence and stop if resistance is abnormal.','Never lever against a battery or improvise a puncture risk.'],
 ['Anti-static FRU storage bags','package','Protect removed ESD-sensitive parts.','Part transport and temporary storage.','Label and store the actual FRU in approved packaging.','Do not use conductive packaging as a work surface on powered equipment.'],
 ['Known-good Ethernet cable kit','cable','Isolate cable-related link faults.','Wired connection unavailable or unstable.','Compare a verified compatible cable while retaining original test conditions.','Respect cable category and site patching policy.'],
 ['Network cable continuity tester','cable','Check supported cable continuity and wire mapping.','Suspected physical copper cabling fault.','Disconnect and test according to the tester instructions; record its result.','Continuity alone does not certify performance; confirm powered/PoE compatibility before connection.'],
 ['Approved known-good USB peripheral','usb','Compare USB port and peripheral behavior.','Single USB device or port unavailable.','Test one known-good approved device on affected and alternate ports.','Do not insert unknown USB devices or bypass device-control policy.'],
 ['Manufacturer printer self-test page','printer','Separate print-engine faults from client/queue issues.','Printer offline reports or poor output quality.','Use the exact model built-in print-test procedure and retain evidence.','Do not enter service modes or reset counters without authorization.'],
 ['Windows Event Viewer','list','Inspect time-correlated application and system evidence.','Crashes, service errors and unexpected restart investigation.','Filter the relevant log and time range; export only approved evidence.','Logs may contain names, addresses and sensitive application information.'],
 ['Windows Reliability Monitor','activity','Review recorded failures and change history.','Correlate a reported fault with software changes.','Open Reliability Monitor and inspect events around the reported time.','A correlation is not proof of the root cause.'],
 ['Windows Device Manager','cpu','Inspect device state and driver details.','Missing peripheral or device error.','Record exact status and hardware identity before changing a driver.','Do not uninstall unrelated devices or disable required security hardware.'],
 ['Windows Task Manager','activity','Inspect resource use and application state.','Performance baseline collection.','Compare CPU, memory, disk and network behavior during the affected workload.','Avoid ending system or business-critical processes without approval.'],
 ['Approved bootable diagnostic media','hard-drive','Run manufacturer-supported hardware tests outside the OS.','Distinguish OS behavior from component failure.','Create verified model-compatible media using official guidance; save test IDs.','Confirm boot authorization and recovery-key availability; do not overwrite user disks.'],
 ['Manufacturer parts compatibility lookup','search','Verify compatible replacement FRUs.','Before ordering or installing a replacement.','Use actual machine type/serial and compare the approved FRU listing: https://support.lenovo.com/us/en/parts-lookup','Do not select a part from family name alone or expose serials publicly.'],
 ['Authorized encrypted backup destination','hard-drive','Protect critical data before risky repair or recovery.','Before storage replacement, recovery or potentially destructive changes.','Use the organization-approved destination and verify accessible backup content.','Do not copy customer data to personal media or unapproved cloud storage.'],
 ['Service inspection light','flashlight','Inspect external connector and physical condition.','Visual intake and damage inspection.','Inspect without probing energized contacts; record only approved photos.','Avoid creating shorts or publishing identifying/customer information.'],
 ['Approved replacement thermal materials','thermometer','Restore specified thermal interfaces during authorized repair.','Only when the model service procedure requires replacement.','Use the documented material and application method for that exact assembly.','Do not reuse prohibited pads or substitute arbitrary thickness/material.'],
 ['Service screw organization tray','package','Prevent misplaced or incorrectly reinstalled fasteners.','Authorized disassembly.','Map screws to the documented location and retain model-specific screw types.','Wrong screw length can damage boards, display assemblies or batteries.'],
 ['Manufacturer display on-screen menu test','monitor','Check whether a display can generate its own menu independently.','Distinguish display power/panel behavior from missing host video.','Open the supported monitor menu and compare with signal connected/disconnected.','A working menu does not prove every display input or cable is healthy.'],
 ['Approved driver package repository','folder-check','Obtain model-compatible, organization-approved drivers.','Confirmed driver remediation or deployment.','Match machine type, OS and signed package using the official/approved repository.','Do not install random driver bundles or disable signature enforcement.'],
];
foreach ($tools as $t) addRow('tools',array_combine(['name','icon','purpose','when_to_use','how_to_use','safety'],$t),'name');
$equipment = [
 ['Lenovo','ThinkPad laptop service reference','laptop','Confirm actual machine type, battery design, approved adapter and supported memory/storage before service.'],
 ['Lenovo','ThinkCentre Tiny service reference','desktop','Confirm Tiny machine type, supported external supply and display outputs. Do not assume tower FRUs apply.'],
 ['Lenovo','ThinkCentre tower or SFF service reference','desktop','Confirm exact chassis and power-supply assembly; FRUs differ between tower and SFF variants.'],
 ['Lenovo','ThinkStation workstation service reference','desktop','Confirm model, supported graphics, memory configuration and diagnostic package before isolation.'],
 ['Lenovo','ThinkVision display service reference','monitor','Confirm exact display model, supported power supply, inputs and USB-C capabilities.'],
 ['Lenovo','USB-C or Thunderbolt dock service reference','other','Confirm exact dock and host compatibility; a USB-C connector alone does not establish video or Thunderbolt support.'],
 ['Generic','Network printer service reference','printer','Identify actual manufacturer/model before selecting consumables, maintenance or reset procedures.'],
 ['Generic','Managed Ethernet switch service reference','switch','Identify model, port capabilities and site configuration. Configuration changes require network-owner approval.'],
 ['Generic','Enterprise access point service reference','access_point','Identify model, controller and approved management process; avoid factory resets during live service.'],
 ['Generic','External power adapter service reference','other','Verify exact device compatibility, voltage, current/wattage and connector through manufacturer guidance.'],
];
foreach ($equipment as $e) addRow('equipment',['manufacturer'=>$e[0],'model_name'=>'Reference only: '.$e[1],'device_type'=>$e[2],'category'=>'Reference family','tools_needed'=>'Model-specific hardware maintenance manual, Manufacturer parts compatibility lookup','repair_guides'=>'Identification:'.$e[3].'|Service scope:This is a reference entry, not an owned asset or verified SKU. No serial, specification or FRU compatibility is implied.|Procedure:Use the exact manufacturer manual and approved diagnostic workflow. Lenovo source: https://pcsupport.lenovo.com/'],'model_name');
$out .= "\nCOMMIT;\n";
$path = __DIR__.'/migrations/20261003_expanded_library.sql';
file_put_contents($path,$out);
echo json_encode(['output'=>$path,'candidate_rows'=>$counts,'total'=>array_sum($counts)],JSON_PRETTY_PRINT)."\n";
