-- Clear existing nodes
DELETE FROM decision_nodes WHERE issue_id IN (1, 14);

-- ===== NO DISPLAY: DIAGNOSTIC QUESTIONS =====
INSERT INTO decision_nodes (id, issue_id, parent_id, yes_next, no_next, question, description, risk, node_type, step_order, is_terminal, result_type, result_solution) VALUES
(100, 1, NULL, 101, 150, 'Is the computer powered on?', 'Check the power LED on the case. Listen for fan spin. Look for any lights or sounds when you press the power button.', 'safe', 'question', 1, 0, NULL, NULL),
(101, 1, 100, 102, 200, 'Do you have access to a multimeter?', 'You will need a digital multimeter to test voltages. If you don''t have one, skip to visual checks.', 'safe', 'question', 2, 0, NULL, NULL),
(102, 1, 101, 103, 250, 'Is the monitor powered on?', 'Check the monitor power LED. Is it on, blinking, or off? Look for any on-screen message.', 'safe', 'question', 3, 0, NULL, NULL),
(103, 1, 102, 104, 300, 'Is the display cable visibly connected?', 'Look at the back of the computer and monitor. Is the cable firmly plugged in at both ends?', 'safe', 'question', 4, 0, NULL, NULL),
(104, 1, 103, 105, 350, 'Do you have a spare display cable or monitor?', 'Having a spare cable or second monitor helps isolate the problem.', 'safe', 'question', 5, 0, NULL, NULL),
(105, 1, 104, 106, 400, 'Can you open the computer case?', 'You will need to open the case to check GPU, RAM, and cables. Unplug first.', 'caution', 'question', 6, 0, NULL, NULL);

-- ===== NO DISPLAY: ACTIONABLE STEPS =====
INSERT INTO decision_nodes (id, issue_id, parent_id, yes_next, no_next, question, description, risk, node_type, step_order, visual_guide, expected_result, tools_needed, is_terminal, result_type, result_solution) VALUES
(200, 1, 101, 201, NULL, 'Step 1: Test PSU Voltage with Multimeter', 'Set multimeter to DC 20V. BLACK probe to any black wire on 24-pin connector. RED probe to GREEN wire. Press power button. Should read 11.5-12.5V.', 'caution', 'step', 10, '24-pin ATX connector: GREEN = PS_ON, BLACK = Ground, YELLOW = 12V, RED = 5V, ORANGE = 3.3V', '12V rail: 11.5-12.5V. 5V rail: 4.75-5.25V. 3.3V rail: 3.14-3.47V.', 'Digital multimeter', 0, NULL, NULL),
(201, 1, 200, NULL, NULL, 'Did the PSU voltages read correctly?', 'Compare readings to expected values.', 'safe', 'step', 11, NULL, 'Voltages within spec = PSU working. Way off = PSU failing.', NULL, 1, 'solved', 'PSU voltages within specification. Power supply is working correctly.'),
(250, 1, 105, 251, NULL, 'Step 2: Reseat the Graphics Card', 'Unplug computer. Press power to discharge. Open case. Locate GPU. Remove screw. Press PCIe clip. Pull card out. Reinsert firmly until clip clicks.', 'caution', 'step', 20, 'GPU is the largest card in PCIe slot. Small plastic clip at slot end. Press to release. Push firmly to reinsert.', 'Computer displays video after reseating.', 'Phillips screwdriver', 0, NULL, NULL),
(251, 1, 250, NULL, NULL, 'Did the display return after reseating GPU?', 'Check if monitor shows BIOS or Windows.', 'safe', 'step', 21, NULL, 'Display returns = GPU was not seated. No display = continue.', NULL, 1, 'solved', 'GPU was not properly seated. Reseating fixed the connection.'),
(300, 1, 103, 301, NULL, 'Step 3: Replace the Display Cable', 'Unplug current cable from both ends. Connect different cable (HDMI/DP/VGA). Ensure both ends click firmly.', 'safe', 'step', 30, 'Cables can fail internally. Try known-good cable. Different port on GPU and monitor.', 'Display shows video with new cable.', 'Spare HDMI/DP/VGA cable', 0, NULL, NULL),
(301, 1, 300, NULL, NULL, 'Did the display work with new cable?', 'Check if monitor shows video.', 'safe', 'step', 31, NULL, 'Works = old cable faulty. No display = continue.', NULL, 1, 'solved', 'Original display cable was faulty. Replacing it restored video.'),
(260, 1, 102, 261, NULL, 'Step 4: Test Monitor Input Source', 'Press menu/input button on monitor. Cycle through inputs (HDMI 1, HDMI 2, DP, VGA). Match to connected cable.', 'safe', 'step', 40, 'Small button on monitor front/side. Navigate to Input Source. Match to cable type.', 'Monitor displays correct input.', 'None', 0, NULL, NULL),
(261, 1, 260, NULL, NULL, 'Did changing input fix the display?', 'Check if monitor shows video.', 'safe', 'step', 41, NULL, 'Works = wrong input was selected. No display = continue.', NULL, 1, 'solved', 'Monitor was set to wrong input. Changing it restored display.'),
(350, 1, 104, 351, NULL, 'Step 5: Test with Integrated Graphics', 'Unplug computer. Remove GPU. Connect display to motherboard video output. Power on.', 'caution', 'step', 50, 'Motherboard video output is near USB ports on back panel. Only works if CPU has integrated graphics. Remove GPU first.', 'Computer displays via motherboard output.', 'Display cable', 0, NULL, NULL),
(351, 1, 350, NULL, NULL, 'Did display work via motherboard?', 'Check if monitor shows video.', 'safe', 'step', 51, NULL, 'Works = GPU is faulty. No display = motherboard/CPU issue.', NULL, 1, 'hardware', 'Dedicated GPU is faulty. Needs replacement.'),
(400, 1, 105, 401, NULL, 'Step 6: Reseat the RAM Modules', 'Unplug computer. Push RAM clips outward. RAM sticks pop up. Pull out. Reinsert firmly until clips click.', 'caution', 'step', 60, 'RAM slots are long slots near CPU. Clips on both ends. Align notch with slot ridge. Push down firmly.', 'Computer boots and displays.', 'None (tool-free)', 0, NULL, NULL),
(401, 1, 400, NULL, NULL, 'Did the display return after reseating RAM?', 'Check if monitor shows BIOS or Windows.', 'safe', 'step', 61, NULL, 'Display returns = RAM was loose. No display = continue.', NULL, 1, 'solved', 'RAM was not properly seated. Reseating restored the connection.');

-- ===== PAPER JAM: DIAGNOSTIC QUESTIONS =====
INSERT INTO decision_nodes (id, issue_id, parent_id, yes_next, no_next, question, description, risk, node_type, step_order, is_terminal, result_type, result_solution) VALUES
(1400, 14, NULL, 1401, 1500, 'Is the paper jam error light on?', 'Check the printer display for paper jam indicator or error message.', 'safe', 'question', 1, 0, NULL, NULL),
(1401, 14, 1400, 1402, 1550, 'Can you open the printer cover?', 'Most printers have a front or top cover. Check if you can open it without force.', 'safe', 'question', 2, 0, NULL, NULL),
(1402, 14, 1401, 1403, 1500, 'Do you see jammed paper inside?', 'Look carefully inside. Check near tray, print head, and rollers.', 'safe', 'question', 3, 0, NULL, NULL),
(1403, 14, 1402, 1404, 1600, 'Is the paper torn or are pieces remaining?', 'After removing main jam, check for small pieces.', 'safe', 'question', 4, 0, NULL, NULL);

-- ===== PAPER JAM: ACTIONABLE STEPS =====
INSERT INTO decision_nodes (id, issue_id, parent_id, yes_next, no_next, question, description, risk, node_type, step_order, visual_guide, expected_result, tools_needed, is_terminal, result_type, result_solution) VALUES
(1500, 14, 1400, 1501, NULL, 'Step 1: Turn Off and Unplug Printer', 'Power off completely. Unplug power cable. Wait 30 seconds.', 'safe', 'step', 10, 'Always unplug before reaching inside. Prevents sudden print head movement.', 'Printer off and unplugged.', 'None', 0, NULL, NULL),
(1501, 14, 1500, 1502, NULL, 'Step 2: Open All Access Panels', 'Open front cover, rear cover, and paper tray extensions. Look for the paper path.', 'safe', 'step', 20, 'Paper path: tray → rollers → print area → output. Check each section.', 'All panels open, path visible.', 'None', 0, NULL, NULL),
(1502, 14, 1501, 1503, NULL, 'Step 3: Gently Remove Jammed Paper', 'Pull paper OUT in feed direction (toward output). Pull slowly. If it tears, stop.', 'caution', 'step', 30, 'NEVER pull backward against feed direction. Always pull forward. If tears, remove pieces individually.', 'Jammed paper removed without tearing.', 'Tweezers for small pieces', 0, NULL, NULL),
(1503, 14, 1502, 1504, NULL, 'Step 4: Clean the Pickup Rollers', 'Dampen lint-free cloth with water/alcohol. Gently wipe rubber pickup rollers.', 'safe', 'step', 40, 'Pickup rollers are rubber wheels near paper tray. Wipe until cloth comes clean.', 'Rollers clean and grip paper.', 'Lint-free cloth, water', 0, NULL, NULL),
(1504, 14, 1503, 1505, NULL, 'Step 5: Realign Paper in Tray', 'Remove all paper. Fan to separate sheets. Reload with guides matching paper size.', 'safe', 'step', 50, 'Guides should touch edges without bending paper. Do not overfill tray.', 'Paper loaded correctly.', 'None', 0, NULL, NULL),
(1505, 14, 1504, 1506, NULL, 'Step 6: Power On and Test Print', 'Plug in. Power on. Wait for initialization. Print test page.', 'safe', 'step', 60, 'Watch display for errors. If jam light stays on, repeat steps 1-5.', 'Printer prints without errors.', 'None', 0, NULL, NULL),
(1506, 14, 1505, NULL, NULL, 'Did the test page print successfully?', 'Check if printer printed without jams.', 'safe', 'step', 61, NULL, 'Test page printed = resolved. Still jamming = hardware issue.', NULL, 1, 'solved', 'Paper jam resolved. After cleaning rollers and realigning paper, printer feeds and prints normally.'),
(1550, 14, 1401, 1551, NULL, 'Step: Check for Physical Obstruction', 'Use flashlight to look inside. Check for paper clips, staples, torn paper, dust clumps.', 'safe', 'step', 70, 'Check under print head, around rollers, in tray slot. Remove objects with tweezers.', 'Path clear of obstructions.', 'Flashlight, tweezers', 0, NULL, NULL),
(1551, 14, 1550, NULL, NULL, 'Did removing obstruction fix it?', 'Power on and check if error clears.', 'safe', 'step', 71, NULL, 'Error clears = obstruction was cause. Persists = hardware failure.', NULL, 1, 'solved', 'Foreign object was causing jam. Printer now operates normally.'),
(1600, 14, 1403, NULL, NULL, 'Professional Repair Required', 'All areas checked. Issue may be broken roller gear, fuser, or internal damage.', 'high', 'step', 100, NULL, NULL, NULL, 1, 'escalation', 'Paper jam persists after all troubleshooting. Hardware failure suspected. Professional repair recommended.');

SELECT 'DONE' as status, COUNT(*) as nodes FROM decision_nodes WHERE issue_id IN (1, 14);
