-- Back up a partially restored database before importing this additive schema patch.
ALTER TABLE `audit_logs` ADD COLUMN IF NOT EXISTS `ip_address` varchar(45) DEFAULT NULL;
ALTER TABLE `audit_logs` ADD COLUMN IF NOT EXISTS `user_agent` text DEFAULT NULL;
ALTER TABLE `audit_logs` ADD COLUMN IF NOT EXISTS `created_at` timestamp NOT NULL DEFAULT current_timestamp();
ALTER TABLE `device_guides` ADD COLUMN IF NOT EXISTS `tools_needed` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL;
ALTER TABLE `device_guides` ADD COLUMN IF NOT EXISTS `safety_notes` text DEFAULT NULL;
ALTER TABLE `device_guides` ADD COLUMN IF NOT EXISTS `author_id` int(11) DEFAULT NULL;
ALTER TABLE `device_guides` ADD COLUMN IF NOT EXISTS `status` enum('draft','published') DEFAULT 'draft';
ALTER TABLE `device_guides` ADD COLUMN IF NOT EXISTS `created_at` timestamp NOT NULL DEFAULT current_timestamp();
ALTER TABLE `device_models` ADD COLUMN IF NOT EXISTS `service_manual_url` varchar(500) DEFAULT NULL;
ALTER TABLE `device_models` ADD COLUMN IF NOT EXISTS `image_url` varchar(500) DEFAULT NULL;
ALTER TABLE `device_models` ADD COLUMN IF NOT EXISTS `known_issues` text DEFAULT NULL;
ALTER TABLE `device_models` ADD COLUMN IF NOT EXISTS `common_failures` text DEFAULT NULL;
ALTER TABLE `device_models` ADD COLUMN IF NOT EXISTS `required_tools` text DEFAULT NULL;
ALTER TABLE `device_models` ADD COLUMN IF NOT EXISTS `created_at` timestamp NOT NULL DEFAULT current_timestamp();
ALTER TABLE `equipment` ADD COLUMN IF NOT EXISTS `notes` text DEFAULT NULL;
ALTER TABLE `equipment` ADD COLUMN IF NOT EXISTS `image_url` varchar(500) DEFAULT NULL;
ALTER TABLE `equipment` ADD COLUMN IF NOT EXISTS `disassembly_guide` text DEFAULT NULL;
ALTER TABLE `equipment` ADD COLUMN IF NOT EXISTS `assembly_guide` text DEFAULT NULL;
ALTER TABLE `equipment` ADD COLUMN IF NOT EXISTS `guide_videos` text DEFAULT NULL;
ALTER TABLE `equipment` ADD COLUMN IF NOT EXISTS `asset_tag` varchar(100) DEFAULT NULL;
ALTER TABLE `equipment` ADD COLUMN IF NOT EXISTS `location` varchar(255) DEFAULT NULL;
ALTER TABLE `equipment` ADD COLUMN IF NOT EXISTS `status` varchar(50) DEFAULT 'active';
ALTER TABLE `equipment` ADD COLUMN IF NOT EXISTS `created_by` int(11) DEFAULT NULL;
ALTER TABLE `equipment` ADD COLUMN IF NOT EXISTS `created_at` timestamp NOT NULL DEFAULT current_timestamp();
ALTER TABLE `equipment` ADD COLUMN IF NOT EXISTS `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp();
ALTER TABLE `equipment` ADD COLUMN IF NOT EXISTS `deleted_at` timestamp NULL DEFAULT NULL;
ALTER TABLE `troubleshooting_issues` ADD COLUMN IF NOT EXISTS `tools_needed` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL;
ALTER TABLE `troubleshooting_issues` ADD COLUMN IF NOT EXISTS `safety_warnings` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL;
ALTER TABLE `troubleshooting_issues` ADD COLUMN IF NOT EXISTS `created_at` timestamp NOT NULL DEFAULT current_timestamp();
ALTER TABLE `troubleshooting_issues` ADD COLUMN IF NOT EXISTS `device_types` varchar(255) DEFAULT NULL;
ALTER TABLE `troubleshooting_issues` ADD COLUMN IF NOT EXISTS `status` varchar(30) DEFAULT 'approved';
ALTER TABLE `troubleshooting_issues` ADD COLUMN IF NOT EXISTS `submitted_by` int(11) DEFAULT NULL;
ALTER TABLE `troubleshooting_sessions` ADD COLUMN IF NOT EXISTS `parts_replaced` text DEFAULT NULL;
ALTER TABLE `troubleshooting_sessions` ADD COLUMN IF NOT EXISTS `tools_used` text DEFAULT NULL;
ALTER TABLE `troubleshooting_sessions` ADD COLUMN IF NOT EXISTS `time_spent_minutes` int(11) DEFAULT NULL;
ALTER TABLE `troubleshooting_sessions` ADD COLUMN IF NOT EXISTS `started_at` timestamp NULL DEFAULT NULL;
ALTER TABLE `troubleshooting_sessions` ADD COLUMN IF NOT EXISTS `ended_at` timestamp NULL DEFAULT NULL;
ALTER TABLE `troubleshooting_sessions` ADD COLUMN IF NOT EXISTS `created_at` timestamp NOT NULL DEFAULT current_timestamp();
ALTER TABLE `troubleshooting_sessions` ADD COLUMN IF NOT EXISTS `resolved_at` timestamp NULL DEFAULT NULL;
ALTER TABLE `troubleshooting_sessions` ADD COLUMN IF NOT EXISTS `escalated_at` timestamp NULL DEFAULT NULL;
ALTER TABLE `troubleshooting_sessions` ADD COLUMN IF NOT EXISTS `total_questions` int(11) DEFAULT 0;
ALTER TABLE `troubleshooting_sessions` ADD COLUMN IF NOT EXISTS `questions_yes` int(11) DEFAULT 0;
ALTER TABLE `troubleshooting_sessions` ADD COLUMN IF NOT EXISTS `questions_no` int(11) DEFAULT 0;
ALTER TABLE `troubleshooting_sessions` ADD COLUMN IF NOT EXISTS `total_steps` int(11) DEFAULT 0;
ALTER TABLE `troubleshooting_sessions` ADD COLUMN IF NOT EXISTS `steps_approved` tinyint(1) DEFAULT 0;
ALTER TABLE `troubleshooting_sessions` ADD COLUMN IF NOT EXISTS `steps_approved_by` varchar(150) DEFAULT NULL;
ALTER TABLE `troubleshooting_steps` ADD COLUMN IF NOT EXISTS `expected_result` text DEFAULT NULL;
ALTER TABLE `troubleshooting_steps` ADD COLUMN IF NOT EXISTS `if_yes` text DEFAULT NULL;
ALTER TABLE `troubleshooting_steps` ADD COLUMN IF NOT EXISTS `if_no` text DEFAULT NULL;
ALTER TABLE `troubleshooting_steps` ADD COLUMN IF NOT EXISTS `required_tools` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL;
ALTER TABLE `troubleshooting_steps` ADD COLUMN IF NOT EXISTS `commands` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL;
ALTER TABLE `troubleshooting_steps` ADD COLUMN IF NOT EXISTS `media_url` varchar(500) DEFAULT NULL;
ALTER TABLE `troubleshooting_steps` ADD COLUMN IF NOT EXISTS `is_final` tinyint(1) DEFAULT 0;
ALTER TABLE `troubleshooting_steps` ADD COLUMN IF NOT EXISTS `created_at` timestamp NOT NULL DEFAULT current_timestamp();
