<?php
define('APP_ROOT', dirname(__DIR__));
require_once APP_ROOT . '/config/app.php';
require_once APP_ROOT . '/includes/helpers.php';
require_once APP_ROOT . '/includes/Database.php';

$updates = [
    'Latitude 5520' => ['image_url'=>'https://i.dell.com/images/dell-product-images/latitude/5520/laptop-latitude-5520-hero.png','disassembly_guide'=>'1. Power off, disconnect power|2. Remove 10 bottom screws (3 longer near hinges)|3. Pry from front edge|4. Release clips around perimeter|5. Lift bottom cover|6. DISCONNECT BATTERY FIRST|7. RAM: spread clips, pull at 30°|8. SSD: 1 screw, slide out|9. WiFi: 1 screw, pop antenna connectors straight up|10. Keyboard: 3 screws from bottom marked K|11. Fan: 1 screw + cable','assembly_guide'=>'1. Apply thermal paste (pea-sized dot)|2. Align heatsink, tighten 4 screws diagonal|3. Connect fan cable|4. Insert WiFi card + antennas (White=Main)|5. Insert RAM at 30°, press to click|6. Insert SSD + screw|7. Connect battery|8. Place keyboard, secure 3 screws|9. Align panel, press clips|10. Secure 10 screws'],
    'Latitude 7430' => ['image_url'=>'https://i.dell.com/images/dell-product-images/latitude/7430/laptop-latitude-7430-hero.png','disassembly_guide'=>'1. Power off, unplug|2. Remove 7 screws (3 captive near hinges)|3. Pry bottom panel from front|4. Disconnect battery cable|5. SSD: 1 screw under panel|6. WiFi: 1 screw, 2 pop connectors','assembly_guide'=>'1. WiFi card + antennas + screw|2. SSD + screw|3. Battery cable|4. Panel clips + 7 screws'],
    'ProBook 450 G9' => ['image_url'=>'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08504650.png','disassembly_guide'=>'1. Power off and unplug|2. Remove rubber feet to access 2 hidden screws (total 7)|3. Remove all screws|4. Pry from rear hinge area|5. Disconnect battery cable|6. RAM: 2 SO-DIMM slots|7. SSD: M.2, 1 screw|8. WiFi: 1 screw, 2 antenna cables|9. Fan: 2 screws + cable','assembly_guide'=>'1. WiFi card + antennas + screw|2. RAM at 30°, press to click|3. SSD + screw|4. Battery cable|5. Panel clips + screws + rubber feet'],
    'EliteBook 840 G10' => ['image_url'=>'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08750849.png','disassembly_guide'=>'1. Power off, disconnect|2. Remove 5 captive screws|3. Pry bottom panel|4. Disconnect battery|5. SSD: 2x M.2 slots|6. WiFi: AX211, 2 antennas','assembly_guide'=>'1. WiFi module + antennas + screw|2. SSD + screw|3. Battery cable|4. Panel + 5 screws'],
    'OptiPlex 7090' => ['image_url'=>'https://i.dell.com/images/dell-product-images/optiplex/7090/desktop-optiplex-7090-hero.png','disassembly_guide'=>'1. Power off, unplug|2. Remove rear thumbscrew|3. Slide side panel off|4. RAM: 4 DIMM slots|5. GPU: PCIe x16, bracket screws|6. M.2 SSD: 1 screw|7. PSU: 4 screws + all connectors','assembly_guide'=>'1. RAM modules (align notch)|2. M.2 SSD + screw|3. GPU in PCIe slot|4. PSU + all connectors|5. Side panel + thumbscrew'],
    'OptiPlex 7010 SFF' => ['image_url'=>'https://i.dell.com/images/dell-product-images/optiplex/7010/desktop-optiplex-7010-hero.png','disassembly_guide'=>'1. Power off, unplug|2. Pull release latch|3. Slide panel off|4. RAM: 2 DDR5 DIMM slots|5. SSD: 2x M.2 slots|6. CPU cooler: clip retention','assembly_guide'=>'1. RAM in DDR5 slots|2. M.2 SSDs|3. Cooler + paste|4. Panel + latch'],
    'LaserJet Pro M404dn' => ['image_url'=>'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c06579555.png','disassembly_guide'=>'1. Turn off, unplug|2. Open rear door|3. Remove fuser (green handles)|4. Remove toner (pull straight)|5. Check pickup roller|6. Clean rollers with lint-free cloth|7. Inspect transfer belt','assembly_guide'=>'1. Clean rollers|2. Reinstall pickup roller|3. Insert toner (click)|4. Align fuser (green handles lock)|5. Close rear door|6. Print test page'],
    'Color LaserJet Pro MFP M283fdw' => ['image_url'=>'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c06596707.png','disassembly_guide'=>'1. Power off, unplug|2. Open rear door|3. Release fuser (2 green levers)|4. Remove 4 toner cartridges|5. Handle transfer belt by edges|6. Clean ADF roller|7. Check scanner glass','assembly_guide'=>'1. Clean transfer belt|2. Reinstall fuser (2 levers)|3. Insert 4 cartridges (K-C-M-Y)|4. Close rear door|5. Clean scanner glass|6. Power on, run calibration'],
    'HL-L2350DW' => ['image_url'=>'https://assets.brother.com/en/v1/articleimages/large/HLL2350DW_main%402x.png','disassembly_guide'=>'1. Power off, unplug|2. Open front cover|3. Pull drum + toner assembly|4. Separate toner from drum (green lever)|5. Clean pickup roller with alcohol|6. Remove waste toner box','assembly_guide'=>'1. Insert toner into drum (click)|2. Slide assembly into printer|3. Close front cover|4. Reinstall waste toner box|5. Print test page'],
    'Catalyst 2960-X' => ['image_url'=>'https://www.cisco.com/c/dam/en/us/products/collateral/switches/catalyst-2960-x-series-switches/nb-06-cat2960x-bb-cte-en-ag.html','disassembly_guide'=>'1. Console: connect rollover cable|2. Check IOS: show version|3. Fan module: pull tab|4. PSU: slide out|5. SFP: pull tab, slide out|6. Flash: dir flash:','assembly_guide'=>'1. SFP modules (click to lock)|2. PSU into bay|3. Fan module|4. Verify ports (green LED)|5. Write memory'],
    'UniFi AP AC Pro' => ['image_url'=>'https://static.ui.com/assets/images/uap-ac-pro/v2/uap-ac-pro@2x.png','disassembly_guide'=>'1. Disconnect PoE cable|2. Twist counter-clockwise from bracket|3. Reset: hold 10+ seconds|4. Check Ethernet port|5. Clean exterior','assembly_guide'=>'1. Align bracket tabs|2. Twist clockwise to lock|3. Connect PoE Ethernet|4. Wait for LED status|5. Verify in UniFi controller'],
    'TL-SG2008' => ['image_url'=>'https://static.tp-link.com/2022/202211/20221109/TL-SG2008_normal_1731020420103w.png','disassembly_guide'=>'1. Power off, unplug|2. Remove 4 bottom screws|3. Lift top cover|4. Check port connections|5. Reset: hold 10+ seconds','assembly_guide'=>'1. Align cover|2. Secure 4 screws|3. Connect power and network|4. Access web UI at 192.168.0.1'],
    'DS-2CD2143G2-I' => ['image_url'=>'https://www.hikvision.com/content/dam/hikvision/products/DS-2CD2143G2-I/images/DS-2CD2143G2-I_front.png','disassembly_guide'=>'1. Disconnect PoE|2. Remove 3 bracket screws|3. Lower camera|4. Open housing (4 screws)|5. Access microSD|6. Reset: hold 15s|7. Check RJ-45|8. Inspect IR LEDs|9. Clean lens','assembly_guide'=>'1. Verify PoE power|2. Mount bracket (3 screws + anchors)|3. Twist-lock camera|4. Secure housing|5. Verify LED|6. Check live feed|7. Adjust angle|8. Enable motion detection'],
    'DS-7608NI-K2/8P' => ['image_url'=>'https://www.hikvision.com/content/dam/hikvision/products/DS-7608NI-K2/images/DS-7608NI-K2_front.png','disassembly_guide'=>'1. Power off, unplug|2. Remove 4 top cover screws|3. Slide cover back|4. Check HDD connections|5. Verify RAM|6. Check PoE LEDs|7. Clean fan|8. Reset: hold 15s','assembly_guide'=>'1. Verify HDD connections|2. Secure HDD in bay|3. Replace cover + 4 screws|4. Connect PoE cameras|5. Connect Ethernet|6. Power on, setup wizard|7. Verify all channels'],
    'IPC-HDW5442T-AS' => ['image_url'=>'https://www.dahuasecurity.com/uploads/image/products/IPC-HDW5442T-AS/IPC-HDW5442T-AS_main.png','disassembly_guide'=>'1. Disconnect PoE|2. Remove from bracket|3. Open housing|4. Reset: hold 15s|5. Check microSD|6. Verify audio|7. Clean lens|8. Check RJ-45','assembly_guide'=>'1. Mount bracket|2. Lock camera|3. Secure housing|4. Connect PoE|5. Verify live feed|6. Enable smart events|7. Enable audio|8. Sync time'],
    'PowerEdge T350' => ['image_url'=>'https://i.dell.com/images/dell-product-images/servers/poweredge-t350/server-poweredge-t350-hero.png','disassembly_guide'=>'1. Power off from front or iDRAC|2. Disconnect power cables|3. Remove top cover (2 thumbscrews)|4. Ground with ESD strap|5. Check RAID battery|6. Remove HDD caddy|7. RAM: push clips|8. Check fans|9. Verify iDRAC port','assembly_guide'=>'1. Install RAM (ECC, match pairs)|2. Insert HDD into caddy + bay|3. Verify RAID card seated|4. Connect power cables|5. Verify fans|6. Connect iDRAC cable|7. Replace cover|8. Power on, check iDRAC|9. Check PERC RAID|10. Monitor temps'],
    'ProLiant ML30 Gen10+' => ['image_url'=>'https://www.hpe.com/content/dam/hpe/servers/proliant-ml-servers/product-images/ML30_Gen10_plus.png','disassembly_guide'=>'1. Power off, disconnect|2. Remove latch, slide cover off|3. Check iLO5 status|4. RAM: 4 DIMM slots|5. HDD: 4x LFF caddies|6. Check Smart Array cache|7. Check IML for errors|8. Verify PSU LED','assembly_guide'=>'1. Install ECC RAM (matched pairs)|2. Insert HDD caddies|3. Verify Smart Array seated|4. Connect all cables|5. Replace cover|6. Access iLO5|7. Check IML|8. Run Smart Storage Admin'],
];

$count = 0;
foreach ($updates as $modelName => $info) {
    $eq = Database::fetch("SELECT id FROM equipment WHERE model_name = ? AND deleted_at IS NULL", [$modelName]);
    if (!$eq) { echo "SKIP: $modelName\n"; continue; }
    Database::update('equipment', $info, 'id = ?', [$eq['id']]);
    $count++;
    echo "OK: $modelName\n";
}
echo "\nDone! Updated {$count} items.\n";
