<?php
/**
 * Comprehensive Demo Data Engine
 * Provides all data for every feature in demo mode
 */

class DemoData {
    
    // ===== TROUBLESHOOTING CATEGORIES =====
    public static function categories() {
        return [
            ['id' => 1, 'name' => 'Display', 'icon' => 'monitor', 'color' => 'blue', 'issue_count' => 3, 'description' => 'Monitor and display issues'],
            ['id' => 2, 'name' => 'Power', 'icon' => 'power', 'color' => 'red', 'issue_count' => 2, 'description' => 'Power and startup issues'],
            ['id' => 3, 'name' => 'Sound', 'icon' => 'volume-2', 'color' => 'purple', 'issue_count' => 1, 'description' => 'Audio and sound issues'],
            ['id' => 4, 'name' => 'Network', 'icon' => 'wifi', 'color' => 'green', 'issue_count' => 3, 'description' => 'Network connectivity issues'],
            ['id' => 5, 'name' => 'Printer', 'icon' => 'printer', 'color' => 'orange', 'issue_count' => 3, 'description' => 'Printer and print issues'],
            ['id' => 6, 'name' => 'CCTV', 'icon' => 'camera', 'color' => 'yellow', 'issue_count' => 2, 'description' => 'Camera and surveillance issues'],
            ['id' => 7, 'name' => 'Software', 'icon' => 'settings', 'color' => 'indigo', 'issue_count' => 4, 'description' => 'Software and OS issues'],
            ['id' => 8, 'name' => 'Hardware', 'icon' => 'cpu', 'color' => 'pink', 'issue_count' => 2, 'description' => 'Hardware component issues'],
        ];
    }
    
    // ===== TROUBLESHOOTING ISSUES =====
    public static function issues() {
        return [
            // Display
            ['id' => 1, 'category_id' => 1, 'title' => 'No Display', 'severity' => 'high', 'icon' => 'monitor-x', 'has_wizard' => true,
             'symptoms' => ['Monitor shows no signal', 'Black screen after boot', 'Display cable connected but nothing shown']],
            ['id' => 2, 'category_id' => 1, 'title' => 'Flickering Display', 'severity' => 'medium', 'icon' => 'zap', 'has_wizard' => true,
             'symptoms' => ['Screen flashes intermittently', 'Horizontal lines appear', 'Display cuts in and out']],
            ['id' => 3, 'category_id' => 1, 'title' => 'Wrong Resolution', 'severity' => 'low', 'icon' => 'scaling', 'has_wizard' => false,
             'symptoms' => ['Display stretched or blurry', 'Cannot change resolution', 'Resolution locked']],
            // Power
            ['id' => 4, 'category_id' => 2, 'title' => 'No Power', 'severity' => 'critical', 'icon' => 'power', 'has_wizard' => true,
             'symptoms' => ['Device does not turn on', 'No LED lights', 'No fan spin']],
            ['id' => 5, 'category_id' => 2, 'title' => 'Random Shutdowns', 'severity' => 'high', 'icon' => 'power-off', 'has_wizard' => true,
             'symptoms' => ['Computer shuts down unexpectedly', 'Blue screen then shutdown', 'Random power loss']],
            // Sound
            ['id' => 6, 'category_id' => 3, 'title' => 'No Sound', 'severity' => 'medium', 'icon' => 'volume-x', 'has_wizard' => true,
             'symptoms' => ['No audio output', 'Speakers not working', 'Headphone jack no sound']],
            // Network
            ['id' => 7, 'category_id' => 4, 'title' => 'No Internet', 'severity' => 'high', 'icon' => 'wifi-off', 'has_wizard' => true,
             'symptoms' => ['Cannot browse websites', 'No network connection', 'Limited connectivity']],
            ['id' => 8, 'category_id' => 4, 'title' => 'Slow Network', 'severity' => 'medium', 'icon' => 'gauge', 'has_wizard' => false,
             'symptoms' => ['Pages load slowly', 'Download speed low', 'Lag during video calls']],
            ['id' => 9, 'category_id' => 4, 'title' => 'WiFi Not Connecting', 'severity' => 'medium', 'icon' => 'wifi', 'has_wizard' => false,
             'symptoms' => ['Cannot see WiFi networks', 'Authentication fails', 'Connected but no internet']],
            // Printer
            ['id' => 10, 'category_id' => 5, 'title' => 'Printer Offline', 'severity' => 'high', 'icon' => 'printer', 'has_wizard' => true,
             'symptoms' => ['Printer shows offline', 'Cannot send print jobs', 'Queue stuck']],
            ['id' => 11, 'category_id' => 5, 'title' => 'Paper Jam', 'severity' => 'medium', 'icon' => 'file-warning', 'has_wizard' => false,
             'symptoms' => ['Paper stuck in printer', 'Cannot feed paper', 'Multiple sheets feeding']],
            ['id' => 12, 'category_id' => 5, 'title' => 'Poor Print Quality', 'severity' => 'low', 'icon' => 'image', 'has_wizard' => false,
             'symptoms' => ['Faded text', 'Streaks on prints', 'Colors look wrong']],
            // CCTV
            ['id' => 13, 'category_id' => 6, 'title' => 'Camera Offline', 'severity' => 'high', 'icon' => 'camera-off', 'has_wizard' => true,
             'symptoms' => ['No video feed', 'Camera not responding', 'NVR shows camera offline']],
            ['id' => 14, 'category_id' => 6, 'title' => 'No Recording', 'severity' => 'high', 'icon' => 'video-off', 'has_wizard' => false,
             'symptoms' => ['NVR not recording', 'Storage full', 'Playback shows gaps']],
            // Software
            ['id' => 15, 'category_id' => 7, 'title' => 'Blue Screen (BSOD)', 'severity' => 'critical', 'icon' => 'alert-triangle', 'has_wizard' => true,
             'symptoms' => ['Blue screen with error code', 'System crashes', 'Automatic restart']],
            ['id' => 16, 'category_id' => 7, 'title' => 'Slow Performance', 'severity' => 'medium', 'icon' => 'gauge', 'has_wizard' => true,
             'symptoms' => ['Computer runs slowly', 'Applications freeze', 'High CPU usage']],
            ['id' => 17, 'category_id' => 7, 'title' => 'Application Crash', 'severity' => 'medium', 'icon' => 'app-window-x', 'has_wizard' => false,
             'symptoms' => ['Application closes unexpectedly', 'Error message appears', 'Program not responding']],
            ['id' => 18, 'category_id' => 7, 'title' => 'Windows Update Failed', 'severity' => 'medium', 'icon' => 'refresh-cw', 'has_wizard' => false,
             'symptoms' => ['Update stuck at percentage', 'Update error code', 'System loops restarting']],
            // Hardware
            ['id' => 19, 'category_id' => 8, 'title' => 'Overheating', 'severity' => 'high', 'icon' => 'thermometer', 'has_wizard' => false,
             'symptoms' => ['Fan running at max speed', 'Hot to touch', 'Thermal shutdown']],
            ['id' => 20, 'category_id' => 8, 'title' => 'Hard Drive Failing', 'severity' => 'critical', 'icon' => 'hard-drive', 'has_wizard' => false,
             'symptoms' => ['Clicking noise from drive', 'Very slow file access', 'Blue screen on boot']],
        ];
    }
    
    // ===== DECISION TREE NODES =====
    // Each issue has a full decision tree with yes/no branching
    public static function decisionTree($issueId) {
        $trees = [
            // ===== NO DISPLAY TREE =====
            1 => [
                ['id' => 1, 'node' => 1, 'question' => 'Is the computer powered on?', 'instruction' => 'Check if the power LED is on and fans are spinning.',
                 'risk' => 'safe', 'why' => 'A powered-off computer obviously has no display output.',
                 'expected_yes' => 'Computer is ON, fans spinning, LEDs on', 'expected_no' => 'Computer is OFF — this is a power issue, not display',
                 'yes_next' => 2, 'no_next' => 'redirect_power'],
                ['id' => 2, 'node' => 2, 'question' => 'Is the monitor powered on?', 'instruction' => 'Check the monitor power LED and power cable.',
                 'risk' => 'safe', 'why' => 'The monitor needs power to display anything.',
                 'expected_yes' => 'Monitor LED is ON (usually green/blue)', 'expected_no' => 'Monitor LED is OFF — check power cable and outlet',
                 'yes_next' => 3, 'no_next' => 'solved_power_cable'],
                ['id' => 3, 'node' => 3, 'question' => 'Is the correct input source selected on the monitor?', 'instruction' => 'Press the input/source button on the monitor. Try HDMI, DisplayPort, VGA.',
                 'risk' => 'safe', 'why' => 'Wrong input source means the monitor ignores the actual video signal.',
                 'expected_yes' => 'Tried all inputs, still no display', 'expected_no' => 'Display appeared after selecting correct input',
                 'yes_next' => 4, 'no_next' => 'solved_input_source'],
                ['id' => 4, 'node' => 4, 'question' => 'Is the display cable properly connected and not damaged?', 'instruction' => 'Unplug and re-plug the display cable on BOTH ends. Check for bent pins or damage.',
                 'risk' => 'safe', 'why' => 'Loose or damaged cables are the #1 cause of no display.',
                 'expected_yes' => 'Cable looks fine, reseated both ends — still no display', 'expected_no' => 'Reseating cable restored the display',
                 'yes_next' => 5, 'no_next' => 'solved_cable'],
                ['id' => 5, 'node' => 5, 'question' => 'Does an external monitor show display?', 'instruction' => 'Connect a different monitor or TV to the same video port.',
                 'risk' => 'safe', 'why' => 'This isolates whether the problem is the original monitor or the computer.',
                 'expected_yes' => 'External monitor shows display — original monitor is faulty', 'expected_no' => 'External monitor also shows no display — computer issue',
                 'yes_next' => 'solved_monitor_fault', 'no_next' => 6],
                ['id' => 6, 'node' => 6, 'question' => 'Do you hear beep codes or see diagnostic LEDs on the motherboard?', 'instruction' => 'Listen carefully for beeps when powering on. Check for blinking LED patterns.',
                 'risk' => 'safe', 'why' => 'Beep codes and LED patterns indicate specific hardware failures (RAM, GPU, CPU).',
                 'expected_yes' => 'Beeps or LED patterns heard/seen — match with manufacturer codes', 'expected_no' => 'No beeps, no LED patterns — power is reaching but nothing is detected',
                 'yes_next' => 7, 'no_next' => 8],
                ['id' => 7, 'node' => 7, 'question' => 'Have you tried reseating the RAM modules?', 'instruction' => 'Power off, unplug, open case, remove RAM, firmly reseat it. Try one stick at a time.',
                 'risk' => 'caution', 'why' => 'Loose RAM is a very common cause of no display. Always test one module at a time.',
                 'tool' => 'Phillips screwdriver, anti-static wrist strap',
                 'expected_yes' => 'RAM reseated — still no display', 'expected_no' => 'Display returned after reseating RAM',
                 'yes_next' => 9, 'no_next' => 'solved_ram'],
                ['id' => 8, 'node' => 8, 'question' => 'Have you tried a different display cable (HDMI/DP/VGA)?', 'instruction' => 'Use a known-good cable from another workstation.',
                 'risk' => 'safe', 'why' => 'Faulty cables can fail silently without visible damage.',
                 'expected_yes' => 'Different cable used — still no display', 'expected_no' => 'New cable fixed the display',
                 'yes_next' => 9, 'no_next' => 'solved_cable_replaced'],
                ['id' => 9, 'node' => 9, 'question' => 'Have you tried connecting to the integrated graphics port (if available)?', 'instruction' => 'Move the display cable to the motherboard video output (not GPU).',
                 'risk' => 'safe', 'why' => 'This tests if the dedicated GPU is the problem. If integrated works, the GPU may be faulty.',
                 'expected_yes' => 'Integrated graphics also has no display', 'expected_no' => 'Integrated graphics works — GPU may be faulty or needs reseating',
                 'yes_next' => null, 'no_next' => 'solved_gpu'],
                // Terminal nodes
                ['id' => 100, 'node' => 'solved_input_source', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Incorrect Input Source',
                 'detail' => 'The monitor was not set to the correct input. After selecting the proper source (HDMI/DP/VGA), the display was restored.',
                 'solution' => 'Set the monitor input source to match the connected cable.'],
                ['id' => 101, 'node' => 'solved_power_cable', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Monitor Power Issue',
                 'detail' => 'The monitor was not powered on. After connecting the power cable properly, the display works.',
                 'solution' => 'Ensure the monitor power cable is firmly connected to both the monitor and the wall outlet/UPS.'],
                ['id' => 102, 'node' => 'solved_cable', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Display Cable Issue',
                 'detail' => 'The display cable was loose or disconnected. Reseating the cable restored the connection.',
                 'solution' => 'Ensure all display cables are firmly connected at both ends.'],
                ['id' => 103, 'node' => 'solved_monitor_fault', 'is_terminal' => true, 'result' => 'hardware_replacement',
                 'message' => 'Diagnosis: Monitor Faulty',
                 'detail' => 'The original monitor does not display, but an external monitor works. The original monitor may be faulty.',
                 'solution' => 'Replace the monitor or send for manufacturer repair.'],
                ['id' => 104, 'node' => 'solved_ram', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: RAM Issue',
                 'detail' => 'Reseating the RAM modules resolved the no display issue.',
                 'solution' => 'Ensure RAM is properly seated. Consider running memtest86 to check for faulty modules.'],
                ['id' => 105, 'node' => 'solved_cable_replaced', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Faulty Cable',
                 'detail' => 'The original display cable was faulty. Replacing it resolved the issue.',
                 'solution' => 'Use the new cable permanently. Dispose of the faulty cable.'],
                ['id' => 106, 'node' => 'solved_gpu', 'is_terminal' => true, 'result' => 'hardware_replacement',
                 'message' => 'Diagnosis: GPU or Motherboard Issue',
                 'detail' => 'Neither dedicated GPU nor integrated graphics produce display. This suggests a motherboard or more fundamental hardware issue.',
                 'solution' => 'Escalate for advanced hardware diagnosis. The motherboard may need to be replaced.'],
                ['id' => 107, 'node' => 'redirect_power', 'is_terminal' => true, 'result' => 'redirect',
                 'message' => 'Redirecting: This is a Power issue, not a Display issue.',
                 'detail' => 'The computer is not powered on. Please use the "No Power" troubleshooting guide instead.',
                 'solution' => 'Switch to No Power troubleshooting.'],
                ['id' => 108, 'node' => 'escalate', 'is_terminal' => true, 'result' => 'escalated',
                 'message' => 'Escalation Required',
                 'detail' => 'All standard No Display troubleshooting steps have been completed without resolution. The issue requires advanced hardware diagnosis.',
                 'solution' => 'Escalate to supervisor with full troubleshooting report.'],
            ],

            // ===== NO POWER TREE =====
            4 => [
                ['id' => 11, 'node' => 1, 'question' => 'Is the wall outlet working?', 'instruction' => 'Test with a phone charger or another device. Check if the outlet has power.',
                 'risk' => 'safe', 'why' => 'If the outlet has no power, nothing downstream will work.',
                 'expected_yes' => 'Outlet has power — other devices work', 'expected_no' => 'Outlet has no power — check breaker panel',
                 'yes_next' => 2, 'no_next' => 'solved_outlet'],
                ['id' => 12, 'node' => 2, 'question' => 'Is the power strip/UPS turned on?', 'instruction' => 'Check the power strip switch or UPS power button. Look for indicator lights.',
                 'risk' => 'safe', 'why' => 'A switched-off power strip is a surprisingly common issue.',
                 'expected_yes' => 'Power strip is ON, indicator lit', 'expected_no' => 'Power strip was OFF — turned it on',
                 'yes_next' => 3, 'no_next' => 'solved_strip'],
                ['id' => 13, 'node' => 3, 'question' => 'Is the power cable securely connected on both ends?', 'instruction' => 'Check the cable from the computer to the outlet/strip. Also check at the PSU end.',
                 'risk' => 'safe', 'why' => 'A loose power cable is easy to fix and often overlooked.',
                 'expected_yes' => 'Cable firmly connected both ends — still no power', 'expected_no' => 'Cable was loose — reconnected it',
                 'yes_next' => 4, 'no_next' => 'solved_cable'],
                ['id' => 14, 'node' => 4, 'question' => 'Does the PSU have a power switch? Is it in the ON (I) position?', 'instruction' => 'Check the back of the desktop PSU for a switch. It should be set to "I" (on), not "O" (off).',
                 'risk' => 'safe', 'why' => 'PSU switches can be accidentally flipped during maintenance.',
                 'expected_yes' => 'PSU switch is ON — still no power', 'expected_no' => 'PSU switch was OFF — turned it on',
                 'yes_next' => 5, 'no_next' => 'solved_psu_switch'],
                ['id' => 15, 'node' => 5, 'question' => 'For laptops: Is the charger LED on? For desktops: Do any LEDs light up when power button is pressed?',
                 'instruction' => 'Laptop: Check charger indicator. Desktop: Press power button, watch for any LED activity.',
                 'risk' => 'safe', 'why' => 'LED activity tells us if power is reaching the motherboard at all.',
                 'expected_yes' => 'Some LEDs are on — power is reaching the system', 'expected_no' => 'No LEDs at all — complete power failure',
                 'yes_next' => 6, 'no_next' => 7],
                ['id' => 16, 'node' => 6, 'question' => 'Have you tried performing a power drain (static discharge)?', 'instruction' => 'Power off, unplug, hold power button for 30 seconds, release, plug back in, power on.',
                 'risk' => 'safe', 'why' => 'Static charge can prevent booting. Power drain resets the power management circuits.',
                 'expected_yes' => 'Power drain done — still not working normally', 'expected_no' => 'Power drain fixed it!',
                 'yes_next' => 7, 'no_next' => 'solved_drain'],
                ['id' => 17, 'node' => 7, 'question' => 'Have you removed all external devices (USB drives, printers, docks)?', 'instruction' => 'Disconnect everything except power, monitor, and keyboard. Try to boot.',
                 'risk' => 'safe', 'why' => 'A faulty USB device can prevent booting by causing a short or power draw issue.',
                 'expected_yes' => 'All devices removed — still no boot', 'expected_no' => 'Computer boots after removing devices',
                 'yes_next' => 8, 'no_next' => 'solved_external_device'],
                ['id' => 18, 'node' => 8, 'question' => 'For desktops: Do you see any fan spin when you press the power button? For laptops: Does the charging LED work with a known-good charger?',
                 'instruction' => 'Desktop: Watch CPU and case fans for any movement. Laptop: Try a verified working charger.',
                 'risk' => 'safe', 'why' => 'Any fan spin means the PSU is delivering some power.',
                 'expected_yes' => 'Fans spin briefly then stop — possible short or PSU issue', 'expected_no' => 'No fan spin at all — PSU or motherboard failure',
                 'yes_next' => null, 'no_next' => null],
                // Terminal
                ['id' => 110, 'node' => 'solved_outlet', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Outlet Has No Power',
                 'detail' => 'The wall outlet was not providing power. Check the circuit breaker or electrician.',
                 'solution' => 'Reset the circuit breaker. If outlet still dead, call an electrician.'],
                ['id' => 111, 'node' => 'solved_strip', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Power Strip Was Off',
                 'detail' => 'The power strip was turned off. After turning it on, the device powers up.',
                 'solution' => 'Mark the power strip switch position clearly to prevent accidental switching.'],
                ['id' => 112, 'node' => 'solved_cable', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Loose Power Cable',
                 'detail' => 'The power cable was loose. Reconnecting firmly resolved the issue.',
                 'solution' => 'Check all power cable connections periodically.'],
                ['id' => 113, 'node' => 'solved_psu_switch', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: PSU Switch Was Off',
                 'detail' => 'The PSU rocker switch was in the OFF position.',
                 'solution' => 'Label PSU switches clearly. Consider placing a warning label near the switch.'],
                ['id' => 114, 'node' => 'solved_drain', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Static Discharge',
                 'detail' => 'Power drain (static discharge) resolved the issue.',
                 'solution' => 'The system had accumulated static charge in the power management circuits.'],
                ['id' => 115, 'node' => 'solved_external_device', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Faulty External Device',
                 'detail' => 'An external USB device was preventing boot. After removal, the system started normally.',
                 'solution' => 'Test each device individually to identify the faulty one. Replace it.'],
            ],

            // ===== NO SOUND TREE =====
            6 => [
                ['id' => 20, 'node' => 1, 'question' => 'Is the volume turned up and not muted?', 'instruction' => 'Check the speaker icon in the system tray. Click it and ensure volume is above 0% and not muted.',
                 'risk' => 'safe', 'why' => 'Muted or zero volume is the most common cause of "no sound."',
                 'expected_yes' => 'Volume is up, not muted — still no sound', 'expected_no' => 'Volume was muted or at 0% — unmuted it',
                 'yes_next' => 2, 'no_next' => 'solved_muted'],
                ['id' => 21, 'node' => 2, 'question' => 'Is the correct playback device selected?', 'instruction' => 'Right-click the speaker icon > Sound settings. Check that the correct output device is selected.',
                 'risk' => 'safe', 'why' => 'Windows may default to a wrong device (HDMI, Bluetooth, or disconnected headphones).',
                 'expected_yes' => 'Correct device selected — still no sound', 'expected_no' => 'Wrong device was selected — changed it',
                 'yes_next' => 3, 'no_next' => 'solved_wrong_device'],
                ['id' => 22, 'node' => 3, 'question' => 'Are the speakers/headphones physically connected properly?', 'instruction' => 'Check cable connections. Try a different audio port. Test the speakers/headphones on another device.',
                 'risk' => 'safe', 'why' => 'Loose connections or faulty audio ports prevent signal transmission.',
                 'expected_yes' => 'Connections verified — still no sound', 'expected_no' => 'Reconnecting fixed the issue',
                 'yes_next' => 4, 'no_next' => 'solved_connection'],
                ['id' => 23, 'node' => 4, 'question' => 'Does the Windows Audio service show as "Running"?', 'instruction' => 'Press Win+R, type services.msc, find "Windows Audio." Check status is "Running" and Startup Type is "Automatic."',
                 'risk' => 'caution', 'why' => 'If this service stops, all audio on the system stops.',
                 'expected_yes' => 'Service is running — still no sound', 'expected_no' => 'Service was stopped — started it',
                 'yes_next' => 5, 'no_next' => 'solved_service'],
                ['id' => 24, 'node' => 5, 'question' => 'Have you tried updating or reinstalling the audio driver?', 'instruction' => 'Open Device Manager (devmgmt.msc), expand Sound controllers, right-click the audio device and update driver.',
                 'risk' => 'caution', 'why' => 'Corrupted or outdated drivers are a frequent cause of audio failures.',
                 'expected_yes' => 'Driver updated — still no sound', 'expected_no' => 'Driver update restored audio',
                 'yes_next' => 6, 'no_next' => 'solved_driver'],
                ['id' => 25, 'node' => 6, 'question' => 'Have you tested with different speakers or headphones?', 'instruction' => 'Connect a known-good pair of headphones or external speakers.',
                 'risk' => 'safe', 'why' => 'This isolates whether the problem is the audio output device or the computer.',
                 'expected_yes' => 'Different speakers also have no sound — computer issue', 'expected_no' => 'New speakers work — original speakers are faulty',
                 'yes_next' => null, 'no_next' => 'solved_speakers'],
                // Terminal
                ['id' => 120, 'node' => 'solved_muted', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Volume Was Muted',
                 'detail' => 'The system volume was muted or set to zero. Unmuting restored audio.',
                 'solution' => 'Adjust volume to comfortable level. Check application-specific volume too.'],
                ['id' => 121, 'node' => 'solved_wrong_device', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Wrong Playback Device',
                 'detail' => 'Windows was routing audio to the wrong output device (e.g., HDMI, Bluetooth).',
                 'solution' => 'Set the correct default playback device. Disable unused audio outputs to prevent switching.'],
                ['id' => 122, 'node' => 'solved_connection', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Connection Issue',
                 'detail' => 'Audio devices were not properly connected. Reconnecting restored audio.',
                 'solution' => 'Ensure cables are fully inserted into the correct ports (green = line out, pink = mic).'],
                ['id' => 123, 'node' => 'solved_service', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Windows Audio Service Was Stopped',
                 'detail' => 'The Windows Audio service had stopped running. Starting it restored audio.',
                 'solution' => 'Set the Windows Audio service to "Automatic" startup to prevent recurrence.'],
                ['id' => 124, 'node' => 'solved_driver', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Audio Driver Issue',
                 'detail' => 'Updating the audio driver resolved the problem.',
                 'solution' => 'Keep audio drivers updated. Download from the manufacturer website for reliability.'],
                ['id' => 125, 'node' => 'solved_speakers', 'is_terminal' => true, 'result' => 'hardware_replacement',
                 'message' => 'Diagnosis: Speakers/Headphones Faulty',
                 'detail' => 'The original speakers/headphones do not work, but known-good ones work fine.',
                 'solution' => 'Replace the faulty speakers or headphones.'],
            ],

            // ===== NETWORK NO INTERNET TREE =====
            7 => [
                ['id' => 30, 'node' => 1, 'question' => 'Is the network cable properly connected? (for wired) / Is WiFi connected? (for wireless)', 'instruction' => 'Check cable at both ends. For WiFi, check the WiFi icon in system tray.',
                 'risk' => 'safe', 'why' => 'Physical connectivity must be established before anything else.',
                 'expected_yes' => 'Connected — still no internet', 'expected_no' => 'Not connected — reconnected',
                 'yes_next' => 2, 'no_next' => 'solved_cable'],
                ['id' => 31, 'node' => 2, 'question' => 'Can you ping the default gateway? (Run: ipconfig, then ping <gateway IP>)', 'instruction' => 'Open CMD, run "ipconfig" to find Default Gateway. Then run "ping <gateway-ip>".',
                 'risk' => 'safe', 'why' => 'Pinging the gateway tests local network connectivity before internet.',
                 'expected_yes' => 'Gateway ping succeeds — local network is OK', 'expected_no' => 'Gateway ping fails — local network issue',
                 'yes_next' => 3, 'no_next' => 4],
                ['id' => 32, 'node' => 3, 'question' => 'Can you ping 8.8.8.8? (Run: ping 8.8.8.8)', 'instruction' => 'This tests if you can reach the internet by IP address, bypassing DNS.',
                 'risk' => 'safe', 'why' => 'If IP ping works but websites don\'t load, it\'s a DNS issue, not a network issue.',
                 'expected_yes' => '8.8.8.8 ping works — internet is reachable, DNS is the problem', 'expected_no' => '8.8.8.8 ping fails — no internet connectivity',
                 'yes_next' => 5, 'no_next' => 6],
                ['id' => 33, 'node' => 4, 'question' => 'Have you tried running: ipconfig /release then ipconfig /renew?', 'instruction' => 'Open CMD as admin, run "ipconfig /release", wait, then "ipconfig /renew".',
                 'risk' => 'caution', 'why' => 'This forces DHCP to assign a new IP address, resolving many IP conflicts.',
                 'expected_yes' => 'Tried renew — still no gateway connection', 'expected_no' => 'New IP assigned, gateway ping works now',
                 'yes_next' => 7, 'no_next' => 'solved_dhcp'],
                ['id' => 34, 'node' => 5, 'question' => 'Have you flushed the DNS cache? (Run: ipconfig /flushdns)', 'instruction' => 'Run "ipconfig /flushdns" in CMD, then try browsing.',
                 'risk' => 'safe', 'why' => 'Corrupted DNS cache can prevent name resolution.',
                 'expected_yes' => 'DNS flush done — still can\'t browse', 'expected_no' => 'Browsing works after DNS flush',
                 'yes_next' => 8, 'no_next' => 'solved_dns_cache'],
                ['id' => 35, 'node' => 6, 'question' => 'Have you tried: ipconfig /flushdns and switching DNS to 8.8.8.8 and 8.8.4.4?', 'instruction' => 'In Network Settings > adapter properties > IPv4 > set DNS manually to Google DNS.',
                 'risk' => 'caution', 'why' => 'ISP DNS servers can fail. Google DNS (8.8.8.8) is reliable and free.',
                 'expected_yes' => 'DNS changed — still no internet', 'expected_no' => 'Changing DNS fixed internet',
                 'yes_next' => 7, 'no_next' => 'solved_dns_server'],
                ['id' => 36, 'node' => 7, 'question' => 'Have you restarted the network adapter? (Disable then Enable in Network Connections)', 'instruction' => 'Run ncpa.cpl, right-click adapter, Disable, wait 10 seconds, Enable.',
                 'risk' => 'safe', 'why' => 'Restarting the adapter resets the network stack for that interface.',
                 'expected_yes' => 'Adapter restarted — still no connection', 'expected_no' => 'Adapter restart fixed the connection',
                 'yes_next' => 8, 'no_next' => 'solved_adapter_reset'],
                ['id' => 37, 'node' => 8, 'question' => 'Is this affecting other computers on the same network?', 'instruction' => 'Check with a colleague or test on another device at the same location.',
                 'risk' => 'safe', 'why' => 'If multiple computers are affected, the issue is with the network infrastructure (switch/router), not the PC.',
                 'expected_yes' => 'Multiple computers affected — network/switch/router issue', 'expected_no' => 'Only this computer affected — PC-specific issue',
                 'yes_next' => 'escalate_network', 'no_next' => 'escalate_pc'],
                // Terminal
                ['id' => 130, 'node' => 'solved_cable', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Network Not Connected',
                 'detail' => 'The network cable was disconnected or WiFi was not connected. Reconnecting restored internet.',
                 'solution' => 'Ensure cables are secure. Check WiFi credentials.'],
                ['id' => 131, 'node' => 'solved_dhcp', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: DHCP Issue',
                 'detail' => 'Releasing and renewing the IP address resolved the DHCP issue.',
                 'solution' => 'Consider setting a static IP if DHCP issues recur frequently.'],
                ['id' => 132, 'node' => 'solved_dns_cache', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Corrupted DNS Cache',
                 'detail' => 'Flushing the DNS cache resolved the browsing issue.',
                 'solution' => 'Consider flushing DNS cache as a first step for any browsing issues.'],
                ['id' => 133, 'node' => 'solved_dns_server', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: DNS Server Issue',
                 'detail' => 'Switching to Google DNS (8.8.8.8) resolved the name resolution problem.',
                 'solution' => 'Keep Google DNS configured. Document this change for the network team.'],
                ['id' => 134, 'node' => 'solved_adapter_reset', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Network Adapter Issue',
                 'detail' => 'Disabling and re-enabling the network adapter reset the network stack and restored connectivity.',
                 'solution' => 'If this recurs, update the NIC driver from the manufacturer website.'],
            ],

            // ===== PRINTER OFFLINE TREE =====
            10 => [
                ['id' => 40, 'node' => 1, 'question' => 'Is the printer powered on and showing "Ready"?', 'instruction' => 'Check the printer display panel and power LED.',
                 'risk' => 'safe', 'why' => 'An offline or powered-off printer obviously won\'t accept jobs.',
                 'expected_yes' => 'Printer is ON and shows Ready', 'expected_no' => 'Printer is OFF or showing error',
                 'yes_next' => 2, 'no_next' => 'solved_power'],
                ['id' => 41, 'node' => 2, 'question' => 'Can you print a test page from the printer itself (not from the computer)?', 'instruction' => 'Use the printer menu: usually Settings > Print Test Page.',
                 'risk' => 'safe', 'why' => 'A printer self-test confirms the printer hardware works independently of the computer.',
                 'expected_yes' => 'Test page prints OK — printer hardware is fine', 'expected_no' => 'Test page fails — printer has a hardware issue',
                 'yes_next' => 3, 'no_next' => 'solved_printer_hw'],
                ['id' => 42, 'node' => 3, 'question' => 'Is the printer connected via USB or Network?', 'instruction' => 'Check the connection type. USB = cable directly to PC. Network = Ethernet or WiFi.',
                 'risk' => 'safe',
                 'expected_yes' => 'Connected — check further', 'expected_no' => 'Connection type determined',
                 'yes_next' => 4, 'no_next' => 4],
                ['id' => 43, 'node' => 4, 'question' => 'For USB: Try a different USB port. For Network: Can you ping the printer IP?', 'instruction' => 'USB: unplug and try a different port. Network: ping the printer IP address from CMD.',
                 'risk' => 'safe', 'why' => 'USB ports can fail, and network connectivity to the printer must be verified.',
                 'expected_yes' => 'Connection verified — printer still offline', 'expected_no' => 'Connection issue found',
                 'yes_next' => 5, 'no_next' => 'solved_connection'],
                ['id' => 44, 'node' => 5, 'question' => 'Have you restarted the Print Spooler service?', 'instruction' => 'Run services.msc, find "Print Spooler", right-click > Restart.',
                 'risk' => 'caution', 'why' => 'The Print Spooler manages all print jobs. If it hangs, printers appear offline.',
                 'expected_yes' => 'Spooler restarted — printer still offline', 'expected_no' => 'Printer came back online after spooler restart',
                 'yes_next' => 6, 'no_next' => 'solved_spooler'],
                ['id' => 45, 'node' => 6, 'question' => 'Have you removed and re-added the printer?', 'instruction' => 'Go to Settings > Printers, remove the printer, then Add a printer.',
                 'risk' => 'safe', 'why' => 'Re-adding the printer refreshes drivers and connection settings.',
                 'expected_yes' => 'Printer re-added — still shows offline', 'expected_no' => 'Printer works after re-adding',
                 'yes_next' => null, 'no_next' => 'solved_readd'],
                // Terminal
                ['id' => 140, 'node' => 'solved_power', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Printer Power Issue',
                 'detail' => 'The printer was powered off or had a power error.',
                 'solution' => 'Ensure printer is powered on and showing Ready status.'],
                ['id' => 141, 'node' => 'solved_printer_hw', 'is_terminal' => true, 'result' => 'hardware_replacement',
                 'message' => 'Diagnosis: Printer Hardware Failure',
                 'detail' => 'The printer self-test failed, indicating a hardware problem.',
                 'solution' => 'Contact the printer manufacturer for repair or replacement.'],
                ['id' => 142, 'node' => 'solved_connection', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Connection Issue',
                 'detail' => 'The printer connection (USB port or network) was faulty.',
                 'solution' => 'For USB: use the working port. For network: verify IP and switch port.'],
                ['id' => 143, 'node' => 'solved_spooler', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Print Spooler Issue',
                 'detail' => 'Restarting the Print Spooler service restored printer functionality.',
                 'solution' => 'Set Print Spooler to Automatic restart. Check for stuck print jobs.'],
                ['id' => 144, 'node' => 'solved_readd', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Re-added Printer',
                 'detail' => 'Removing and re-adding the printer refreshed all settings and drivers.',
                 'solution' => 'Download the latest driver from the manufacturer website for best results.'],
            ],

            // ===== SLOW PERFORMANCE TREE =====
            16 => [
                ['id' => 50, 'node' => 1, 'question' => 'Is Task Manager showing high CPU usage?', 'instruction' => 'Press Ctrl+Shift+Esc. Check the CPU column. Anything above 80% sustained is high.',
                 'risk' => 'safe', 'why' => 'High CPU usage directly causes slowness. Identifying the process is key.',
                 'expected_yes' => 'High CPU detected — identifying the process', 'expected_no' => 'CPU usage is normal (under 50%)',
                 'yes_next' => 2, 'no_next' => 3],
                ['id' => 51, 'node' => 2, 'question' => 'Can you identify the process causing high CPU? Is it a known application or system process?', 'instruction' => 'In Task Manager, click the CPU column to sort. Check if it\'s an antivirus scan, Windows Update, or unknown process.',
                 'risk' => 'safe',
                 'expected_yes' => 'Identified the process', 'expected_no' => 'Cannot identify',
                 'yes_next' => 'solved_cpu_process', 'no_next' => 4],
                ['id' => 52, 'node' => 3, 'question' => 'Is the disk usage at 100% in Task Manager?', 'instruction' => 'In Task Manager, check the Disk column. 100% disk usage causes extreme slowness.',
                 'risk' => 'safe', 'why' => '100% disk usage (common with failing HDDs or Windows Search) makes the system unusable.',
                 'expected_yes' => 'Disk at 100%', 'expected_no' => 'Disk usage is normal',
                 'yes_next' => 4, 'no_next' => 5],
                ['id' => 53, 'node' => 4, 'question' => 'Have you run a disk health check? (Run: chkdsk C: /f)', 'instruction' => 'Open CMD as admin, run "chkdsk C: /f". It will ask to schedule on reboot — agree and restart.',
                 'risk' => 'caution', 'why' => 'CHKDSK fixes disk errors and bad sectors that cause 100% disk usage.',
                 'expected_yes' => 'CHKDSK ran — check results after reboot', 'expected_no' => 'CHKDSK fixed disk errors',
                 'yes_next' => 5, 'no_next' => 'solved_disk'],
                ['id' => 54, 'node' => 5, 'question' => 'How much free RAM does the system have? (Check Task Manager > Performance > Memory)', 'instruction' => 'If available RAM is consistently under 10% free, the system needs more RAM or has a memory leak.',
                 'risk' => 'safe',
                 'expected_yes' => 'Low RAM — under 10% available', 'expected_no' => 'RAM is sufficient',
                 'yes_next' => 6, 'no_next' => 7],
                ['id' => 55, 'node' => 6, 'question' => 'Have you checked for startup programs that can be disabled?', 'instruction' => 'Open Task Manager > Startup tab. Disable unnecessary programs that slow boot and consume resources.',
                 'risk' => 'caution', 'why' => 'Too many startup programs consume RAM and CPU continuously.',
                 'expected_yes' => 'Startup programs cleaned — still slow', 'expected_no' => 'System is faster after disabling startup apps',
                 'yes_next' => 7, 'no_next' => 'solved_startup'],
                ['id' => 56, 'node' => 7, 'question' => 'Have you run "sfc /scannow" to check for corrupted system files?', 'instruction' => 'Open CMD as admin, run "sfc /scannow". Wait for it to complete.',
                 'risk' => 'caution', 'why' => 'Corrupted system files can cause performance degradation and instability.',
                 'expected_yes' => 'SFC found and repaired files — test if slow persists', 'expected_no' => 'SFC restored system files, performance improved',
                 'yes_next' => null, 'no_next' => 'solved_sfc'],
                // Terminal
                ['id' => 150, 'node' => 'solved_cpu_process', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Resource-Consuming Process Identified',
                 'detail' => 'A specific process was consuming excessive CPU. Adjusting or terminating it restored performance.',
                 'solution' => 'Monitor the process. If it recurs, update or reinstall the application.'],
                ['id' => 151, 'node' => 'solved_disk', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Disk Errors Fixed',
                 'detail' => 'CHKDSK repaired disk errors that were causing 100% disk usage.',
                 'solution' => 'Monitor disk health. Consider upgrading to SSD if using HDD.'],
                ['id' => 152, 'node' => 'solved_startup', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Too Many Startup Programs',
                 'detail' => 'Disabling unnecessary startup programs freed up RAM and CPU resources.',
                 'solution' => 'Only keep essential programs in startup. Most programs don\'t need to auto-start.'],
                ['id' => 153, 'node' => 'solved_sfc', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Corrupted System Files',
                 'detail' => 'SFC repaired corrupted system files that were causing performance issues.',
                 'solution' => 'Run DISM /Online /Cleanup-Image /RestoreHealth if SFC finds issues it can\'t fix.'],
            ],

            // ===== BSOD TREE =====
            15 => [
                ['id' => 60, 'node' => 1, 'question' => 'Does the BSOD show a specific error code? (e.g., IRQL_NOT_LESS_OR_EQUAL)', 'instruction' => 'Note down the exact error code displayed on the blue screen.',
                 'risk' => 'safe', 'why' => 'The error code identifies the specific cause of the crash.',
                 'expected_yes' => 'Error code recorded', 'expected_no' => 'System restarts too fast to read',
                 'yes_next' => 2, 'no_next' => 3],
                ['id' => 61, 'node' => 2, 'question' => 'Does the error mention a specific driver file (ending in .sys)?', 'instruction' => 'The error often shows a file name like "nvlddmkm.sys" or "ntoskrnl.exe".',
                 'risk' => 'safe', 'why' => 'Driver files in the BSOD indicate which hardware/driver is causing the crash.',
                 'expected_yes' => 'Driver file identified', 'expected_no' => 'No specific file shown',
                 'yes_next' => 'solved_driver_bsod', 'no_next' => 4],
                ['id' => 62, 'node' => 3, 'question' => 'Can you boot into Safe Mode? (Press F8 or Shift+Restart)', 'instruction' => 'If the BSOD keeps looping, try booting into Safe Mode. In Safe Mode, check Event Viewer.',
                 'risk' => 'safe', 'why' => 'Safe Mode loads only essential drivers, helping isolate software vs hardware causes.',
                 'expected_yes' => 'Can boot into Safe Mode', 'expected_no' => 'Cannot even reach Safe Mode',
                 'yes_next' => 4, 'no_next' => 'escalate_bsod'],
                ['id' => 63, 'node' => 4, 'question' => 'Have you checked Event Viewer for the crash details? (eventvwr.msc > Windows Logs > System)', 'instruction' => 'Look for Critical or Error events around the time of the BSOD.',
                 'risk' => 'safe', 'why' => 'Event Viewer logs detailed crash information not shown on the blue screen.',
                 'expected_yes' => 'Event details found', 'expected_no' => 'No useful events found',
                 'yes_next' => 5, 'no_next' => 6],
                ['id' => 64, 'node' => 5, 'question' => 'Have you run "sfc /scannow" and "DISM /Online /Cleanup-Image /RestoreHealth"?', 'instruction' => 'Run both commands in CMD as admin. SFC first, then DISM if SFC can\'t fix issues.',
                 'risk' => 'caution', 'why' => 'Corrupted system files are a common BSOD cause.',
                 'expected_yes' => 'Both commands ran — test stability', 'expected_no' => 'Repairs were successful',
                 'yes_next' => 6, 'no_next' => 'solved_repair'],
                ['id' => 65, 'node' => 6, 'question' => 'Have you checked for Windows updates and driver updates?', 'instruction' => 'Check Windows Update and update all device drivers, especially GPU and chipset.',
                 'risk' => 'caution', 'why' => 'Outdated drivers, especially GPU, are the #1 BSOD cause.',
                 'expected_yes' => 'Updates installed — still crashing', 'expected_no' => 'Updates fixed the stability',
                 'yes_next' => null, 'no_next' => 'solved_updates'],
                // Terminal
                ['id' => 160, 'node' => 'solved_driver_bsod', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Driver BSOD',
                 'detail' => 'The BSOD was caused by a specific driver. Updating or rolling back the driver resolved the issue.',
                 'solution' => 'Keep all drivers updated. For GPU drivers, use the manufacturer\'s tool (NVIDIA GeForce Experience, AMD Adrenalin).'],
                ['id' => 161, 'node' => 'solved_repair', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Corrupted System Files',
                 'detail' => 'SFC and DISM repaired corrupted system files causing the BSOD.',
                 'solution' => 'Monitor system stability. If BSODs recur, consider a Windows refresh.'],
                ['id' => 162, 'node' => 'solved_updates', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Outdated Software',
                 'detail' => 'Windows and driver updates resolved the BSOD issue.',
                 'solution' => 'Enable automatic Windows updates. Check for driver updates monthly.'],
                ['id' => 163, 'node' => 'escalate_bsod', 'is_terminal' => true, 'result' => 'escalated',
                 'message' => 'Escalation Required: Persistent BSOD',
                 'detail' => 'The BSOD is too severe for standard troubleshooting. The system cannot boot normally.',
                 'solution' => 'Escalate to senior technician. May require memory testing, HDD/SSD testing, or OS reinstallation.'],
            ],

            // ===== RANDOM SHUTDOWN TREE =====
            5 => [
                ['id' => 70, 'node' => 1, 'question' => 'Is the computer overheating? (Check temperature or feel the vents)', 'instruction' => 'Touch the vents. If extremely hot, or if thermal warnings appear, it\'s overheating.',
                 'risk' => 'safe', 'why' => 'Overheating causes automatic shutdowns to protect hardware.',
                 'expected_yes' => 'Computer is very hot — overheating', 'expected_no' => 'Temperature seems normal',
                 'yes_next' => 2, 'no_next' => 3],
                ['id' => 71, 'node' => 2, 'question' => 'Are the fans spinning freely? Is there dust buildup?', 'instruction' => 'Listen for fan noise. Check if fans are blocked or clogged with dust.',
                 'risk' => 'safe', 'why' => 'Dust-clogged fans can\'t cool effectively.',
                 'expected_yes' => 'Fans are clogged or not spinning properly', 'expected_no' => 'Fans seem fine — other overheating cause',
                 'yes_next' => 'solved_cleaning', 'no_next' => 4],
                ['id' => 72, 'node' => 3, 'question' => 'Does the shutdown happen randomly or during specific tasks (gaming, heavy load)?', 'instruction' => 'Note when it happens — idle, during video playback, during heavy work, etc.',
                 'risk' => 'safe',
                 'expected_yes' => 'Happens during heavy load — possible power supply or heat issue', 'expected_no' => 'Happens randomly — could be hardware or software',
                 'yes_next' => 4, 'no_next' => 5],
                ['id' => 73, 'node' => 4, 'question' => 'Have you checked the Event Viewer for shutdown原因? (eventvwr.msc > System)', 'instruction' => 'Look for Event IDs 41 (kernel-power) or 6008 (unexpected shutdown).',
                 'risk' => 'safe', 'why' => 'Event Viewer logs why the system shut down.',
                 'expected_yes' => 'Event found — indicates power loss or hardware failure', 'expected_no' => 'No useful events',
                 'yes_next' => 5, 'no_next' => 6],
                ['id' => 74, 'node' => 5, 'question' => 'Have you checked the power supply? (For desktops: test with a PSU tester or swap PSU)', 'instruction' => 'A failing PSU can cause random shutdowns under load.',
                 'risk' => 'caution', 'why' => 'PSU failure is the #1 cause of random shutdowns in desktops.',
                 'expected_yes' => 'PSU seems OK', 'expected_no' => 'PSU tested and found faulty',
                 'yes_next' => 6, 'no_next' => 'solved_psu'],
                ['id' => 75, 'node' => 6, 'question' => 'Have you run a memory test? (Windows Memory Diagnostic)', 'instruction' => 'Search for "Windows Memory Diagnostic" in Start. Run it and restart.',
                 'risk' => 'caution', 'why' => 'Faulty RAM can cause random shutdowns and BSODs.',
                 'expected_yes' => 'Memory test complete — check results', 'expected_no' => 'Memory errors found',
                 'yes_next' => null, 'no_next' => 'solved_ram'],
                // Terminal
                ['id' => 170, 'node' => 'solved_cleaning', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Overheating Due to Dust',
                 'detail' => 'Cleaning dust from fans and heatsinks restored proper cooling.',
                 'solution' => 'Clean the computer every 3-6 months. Ensure good ventilation.'],
                ['id' => 171, 'node' => 'solved_psu', 'is_terminal' => true, 'result' => 'hardware_replacement',
                 'message' => 'Diagnosis: Failing Power Supply',
                 'detail' => 'The power supply unit is failing and causing random shutdowns.',
                 'solution' => 'Replace the PSU. Choose one with appropriate wattage and 80+ certification.'],
                ['id' => 172, 'node' => 'solved_ram', 'is_terminal' => true, 'result' => 'hardware_replacement',
                 'message' => 'Diagnosis: Faulty RAM',
                 'detail' => 'Memory test detected errors in the RAM modules.',
                 'solution' => 'Replace the faulty RAM module(s). Run the test again to confirm.'],
            ],

            // ===== CAMERA OFFLINE TREE =====
            13 => [
                ['id' => 80, 'node' => 1, 'question' => 'Is the camera receiving power? (Check LED or PoE status)', 'instruction' => 'Look at the camera LED. For PoE cameras, check the switch port LED.',
                 'risk' => 'safe', 'why' => 'A camera without power obviously won\'t work.',
                 'expected_yes' => 'Camera has power (LED on)', 'expected_no' => 'No power — check PoE switch or power adapter',
                 'yes_next' => 2, 'no_next' => 'solved_power'],
                ['id' => 81, 'node' => 2, 'question' => 'Is the network cable connected and is the switch port active?', 'instruction' => 'Check the Ethernet cable and switch port LED. Try a different port.',
                 'risk' => 'safe', 'why' => 'IP cameras need network connectivity to stream video.',
                 'expected_yes' => 'Network connected, port active', 'expected_no' => 'Network cable or port issue',
                 'yes_next' => 3, 'no_next' => 'solved_network'],
                ['id' => 82, 'node' => 3, 'question' => 'Can you ping the camera\'s IP address from a computer on the same network?', 'instruction' => 'Use CMD: ping <camera-IP>. Check the camera IP in the NVR or network scan.',
                 'risk' => 'safe', 'why' => 'Pinging confirms the camera is reachable on the network.',
                 'expected_yes' => 'Ping succeeds — camera is on network', 'expected_no' => 'Ping fails — network configuration issue',
                 'yes_next' => 4, 'no_next' => 'solved_config'],
                ['id' => 83, 'node' => 4, 'question' => 'Is the camera visible in the NVR/VMS software?', 'instruction' => 'Open the NVR interface and check the camera list. Try re-adding the camera.',
                 'risk' => 'safe',
                 'expected_yes' => 'Camera shows in NVR but no video', 'expected_no' => 'Camera not in NVR at all',
                 'yes_next' => 'solved_nvr_config', 'no_next' => 5],
                ['id' => 84, 'node' => 5, 'question' => 'Have you tried rebooting the camera? (Power cycle or NVR reboot)', 'instruction' => 'Disconnect camera power, wait 10 seconds, reconnect. Or reboot the NVR.',
                 'risk' => 'safe', 'why' => 'A simple reboot fixes many camera connectivity issues.',
                 'expected_yes' => 'Camera rebooted — still offline', 'expected_no' => 'Camera came back online',
                 'yes_next' => null, 'no_next' => 'solved_reboot'],
                // Terminal
                ['id' => 180, 'node' => 'solved_power', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Camera Power Issue',
                 'detail' => 'The camera was not receiving power. Check PoE switch or power adapter.',
                 'solution' => 'Verify PoE switch budget, check power cable/adapter, test different PoE port.'],
                ['id' => 181, 'node' => 'solved_network', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Network Cable/Port Issue',
                 'detail' => 'The network cable or switch port was faulty.',
                 'solution' => 'Replace cable, try different switch port, check cable termination.'],
                ['id' => 182, 'node' => 'solved_config', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Camera Network Configuration',
                 'detail' => 'The camera had a network configuration issue (wrong IP, subnet mismatch).',
                 'solution' => 'Ensure camera IP is in the correct subnet. Use DHCP or set static IP correctly.'],
                ['id' => 183, 'node' => 'solved_nvr_config', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: NVR Configuration',
                 'detail' => 'The NVR was not configured correctly to receive the camera stream.',
                 'solution' => 'Re-add the camera in the NVR with correct protocol and credentials.'],
                ['id' => 184, 'node' => 'solved_reboot', 'is_terminal' => true, 'result' => 'solved',
                 'message' => 'Problem Solved: Camera Needed Reboot',
                 'detail' => 'Power cycling the camera resolved the issue.',
                 'solution' => 'If this recurs frequently, check camera firmware and network stability.'],
            ],
        ];
        
        return $trees[$issueId] ?? null;
    }
    
    // ===== KNOWLEDGE ARTICLES =====
    public static function knowledgeArticles() {
        return [
            ['id' => 1, 'title' => 'How to Fix No Display on Desktop PC', 'category' => 'Display', 'status' => 'published', 'author' => 'System Admin',
             'rating' => 4.7, 'uses' => 137, 'content' => 'Complete guide to diagnosing no display issues on desktop computers.',
             'created' => '2026-08-01', 'updated' => '2026-08-20', 'verified' => true],
            ['id' => 2, 'title' => 'Network Troubleshooting: Complete Guide', 'category' => 'Network', 'status' => 'published', 'author' => 'System Admin',
             'rating' => 4.8, 'uses' => 203, 'content' => 'Comprehensive network troubleshooting from physical layer to DNS.',
             'created' => '2026-07-15', 'updated' => '2026-08-19', 'verified' => true],
            ['id' => 3, 'title' => 'Printer Offline Fix - HP LaserJet Series', 'category' => 'Printer', 'status' => 'published', 'author' => 'Maria Santos',
             'rating' => 4.5, 'uses' => 89, 'content' => 'Step-by-step guide for HP LaserJet offline issues.',
             'created' => '2026-08-05', 'updated' => '2026-08-21', 'verified' => true],
            ['id' => 4, 'title' => 'CCTV Camera Offline - IP Camera Guide', 'category' => 'CCTV', 'status' => 'published', 'author' => 'System Admin',
             'rating' => 4.6, 'uses' => 67, 'content' => 'Diagnosing and fixing IP camera offline issues.',
             'created' => '2026-08-10', 'updated' => '2026-08-18', 'verified' => true],
            ['id' => 5, 'title' => 'BSOD Troubleshooting Guide', 'category' => 'Software', 'status' => 'published', 'author' => 'Juan Dela Cruz',
             'rating' => 4.9, 'uses' => 156, 'content' => 'Systematic approach to resolving Blue Screen of Death errors.',
             'created' => '2026-07-20', 'updated' => '2026-08-22', 'verified' => true],
            ['id' => 6, 'title' => 'Power Issues: No Power Troubleshooting', 'category' => 'Power', 'status' => 'published', 'author' => 'System Admin',
             'rating' => 4.4, 'uses' => 112, 'content' => 'Complete power troubleshooting for desktops and laptops.',
             'created' => '2026-08-02', 'updated' => '2026-08-15', 'verified' => true],
            ['id' => 7, 'title' => 'Slow Computer: Speed Up Windows 10/11', 'category' => 'Software', 'status' => 'published', 'author' => 'System Admin',
             'rating' => 4.3, 'uses' => 198, 'content' => 'Practical steps to improve slow computer performance.',
             'created' => '2026-07-25', 'updated' => '2026-08-20', 'verified' => true],
            ['id' => 8, 'title' => 'Lenovo ThinkPad T14 Gen 3 Disassembly Guide', 'category' => 'Equipment', 'status' => 'published', 'author' => 'System Admin',
             'rating' => 4.8, 'uses' => 45, 'content' => 'Complete disassembly and assembly guide with step-by-step photos.',
             'created' => '2026-08-08', 'updated' => '2026-08-17', 'verified' => true],
            ['id' => 9, 'title' => 'ESD Safety Best Practices for Field IT', 'category' => 'Safety', 'status' => 'published', 'author' => 'System Admin',
             'rating' => 4.6, 'uses' => 78, 'content' => 'Electrostatic discharge prevention guide for field technicians.',
             'created' => '2026-07-30', 'updated' => '2026-08-12', 'verified' => true],
            ['id' => 10, 'title' => 'Windows Recovery: sfc, DISM, and chkdsk Guide', 'category' => 'Software', 'status' => 'draft', 'author' => 'Juan Dela Cruz',
             'rating' => 0, 'uses' => 0, 'content' => 'Using Windows recovery tools to fix system issues.',
             'created' => '2026-08-21', 'updated' => '2026-08-21', 'verified' => false],
        ];
    }
    
    // ===== EQUIPMENT / DEVICES =====
    public static function manufacturers() {
        return [
            ['id' => 1, 'name' => 'Dell', 'logo' => 'laptop', 'model_count' => 8],
            ['id' => 2, 'name' => 'Lenovo', 'logo' => 'laptop', 'model_count' => 6],
            ['id' => 3, 'name' => 'HP', 'logo' => 'printer', 'model_count' => 7],
            ['id' => 4, 'name' => 'Cisco', 'logo' => 'wifi', 'model_count' => 5],
            ['id' => 5, 'name' => 'Hikvision', 'logo' => 'camera', 'model_count' => 4],
            ['id' => 6, 'name' => 'APC', 'logo' => 'battery-charging', 'model_count' => 3],
            ['id' => 7, 'name' => 'Samsung', 'logo' => 'monitor', 'model_count' => 4],
            ['id' => 8, 'name' => 'Ubiquiti', 'logo' => 'wifi', 'model_count' => 3],
        ];
    }
    
    public static function deviceModels() {
        return [
            ['id' => 1, 'manufacturer' => 'Dell', 'model' => 'OptiPlex 7090', 'type' => 'Desktop', 'generation' => '11th Gen Intel',
             'specs' => ['Intel Core i7-11700', '16GB DDR4', '512GB NVMe SSD', 'Intel UHD 750'],
             'known_issues' => ['BIOS firmware updates needed', 'Thunderbolt compatibility'],
             'tools_needed' => ['Phillips screwdriver #1', 'Anti-static wrist strap', 'Plastic pry tool'],
             'manual_url' => 'https://www.dell.com/support'],
            ['id' => 2, 'manufacturer' => 'Lenovo', 'model' => 'ThinkPad T14 Gen 3', 'type' => 'Laptop', 'generation' => '12th Gen Intel',
             'specs' => ['Intel Core i5-1240P', '16GB LPDDR5', '512GB NVMe SSD', '14" FHD IPS'],
             'known_issues' => ['Trackpad sensitivity', 'Battery drain in sleep'],
             'tools_needed' => ['Phillips screwdriver #1', 'Plastic spudger', 'Anti-static wrist strap'],
             'manual_url' => 'https://pcsupport.lenovo.com'],
            ['id' => 3, 'manufacturer' => 'HP', 'model' => 'LaserJet Pro M404dn', 'type' => 'Printer', 'generation' => 'Mono Laser',
             'specs' => ['40 ppm print speed', 'Duplex printing', 'Ethernet/USB', '550-sheet tray'],
             'known_issues' => ['Firmware updates required', 'Toner chip recognition'],
             'tools_needed' => ['Standard tools only', 'Toner cartridge replacement'],
             'manual_url' => 'https://support.hp.com'],
            ['id' => 4, 'manufacturer' => 'Dell', 'model' => 'Latitude 5520', 'type' => 'Laptop', 'generation' => '11th Gen Intel',
             'specs' => ['Intel Core i5-1145G7', '8GB DDR4', '256GB SSD', '15.6" FHD'],
             'known_issues' => ['Thunderbolt dock issues', 'WiFi disconnects'],
             'tools_needed' => ['Phillips screwdriver', 'Anti-static wrist strap'],
             'manual_url' => 'https://www.dell.com/support'],
            ['id' => 5, 'manufacturer' => 'Hikvision', 'model' => 'DS-2CD2143G2-I', 'type' => 'CCTV Camera', 'generation' => 'AcuSense Gen 2',
             'specs' => ['4MP resolution', 'PoE powered', 'IP67 weatherproof', '30m IR range'],
             'known_issues' => ['Firmware update needed for ONVIF compatibility', 'PoE budget considerations'],
             'tools_needed' => ['PoE switch', 'Network cable tester', 'Ladder'],
             'manual_url' => 'https://www.hikvision.com'],
            ['id' => 6, 'manufacturer' => 'HP', 'model' => 'ProBook 450 G9', 'type' => 'Laptop', 'generation' => '12th Gen Intel',
             'specs' => ['Intel Core i5-1235U', '8GB DDR4', '256GB SSD', '15.6" FHD'],
             'known_issues' => ['Fan noise under load', 'BIOS update recommended'],
             'tools_needed' => ['Phillips screwdriver', 'Anti-static strap'],
             'manual_url' => 'https://support.hp.com'],
        ];
    }
    
    // ===== COMMANDS =====
    public static function commands() {
        return [
            ['id' => 1, 'command' => 'ipconfig', 'category' => 'Network', 'risk' => 'safe',
             'description' => 'Display IP configuration for all network adapters',
             'when' => 'When you need to check IP address, subnet mask, default gateway, or DNS servers',
             'example' => 'ipconfig',
             'output' => 'Ethernet adapter: IPv4: 192.168.1.100, Subnet: 255.255.255.0, Gateway: 192.168.1.1',
             'next' => 'If no IP: check DHCP. If IP starts with 169.254: DHCP failed.'],
            ['id' => 2, 'command' => 'ipconfig /all', 'category' => 'Network', 'risk' => 'safe',
             'description' => 'Display detailed IP configuration including MAC address and DHCP info',
             'when' => 'When you need to verify DHCP server, DNS suffix, or MAC address',
             'example' => 'ipconfig /all',
             'output' => 'Full adapter details including DHCP server, lease times, and DNS servers',
             'next' => 'Check DHCP Enabled: Yes/No. Verify DNS servers are correct.'],
            ['id' => 3, 'command' => 'ipconfig /release', 'category' => 'Network', 'risk' => 'caution',
             'description' => 'Release the current IP address from DHCP',
             'when' => 'When troubleshooting IP conflicts or DHCP issues',
             'example' => 'ipconfig /release',
             'output' => 'IP address released, adapter shows 0.0.0.0',
             'next' => 'Follow with ipconfig /renew to get a new IP.'],
            ['id' => 4, 'command' => 'ipconfig /renew', 'category' => 'Network', 'risk' => 'caution',
             'description' => 'Request a new IP address from DHCP server',
             'when' => 'After releasing IP, or when IP conflict detected',
             'example' => 'ipconfig /renew',
             'output' => 'New IP address assigned from DHCP server',
             'next' => 'If fails: check DHCP server, network cable, or set static IP.'],
            ['id' => 5, 'command' => 'ipconfig /flushdns', 'category' => 'Network', 'risk' => 'safe',
             'description' => 'Clear the DNS resolver cache',
             'when' => 'When DNS resolution is incorrect or websites resolve to wrong IPs',
             'example' => 'ipconfig /flushdns',
             'output' => 'Successfully flushed the DNS Resolver Cache',
             'next' => 'Test browsing. If still failing, try changing DNS servers.'],
            ['id' => 6, 'command' => 'ping', 'category' => 'Network', 'risk' => 'safe',
             'description' => 'Test network connectivity to a target host',
             'when' => 'To verify if a host is reachable on the network',
             'example' => 'ping 8.8.8.8  (test internet)\nping 192.168.1.1  (test gateway)\nping 127.0.0.1  (test local TCP/IP stack)',
             'output' => 'Reply from 8.8.8.8: bytes=32 time=12ms TTL=117',
             'next' => 'If timeout: check firewall, cable, or DNS. If reply: connectivity OK.'],
            ['id' => 7, 'command' => 'tracert', 'category' => 'Network', 'risk' => 'safe',
             'description' => 'Trace the route packets take to a destination',
             'when' => 'To identify where network connectivity fails along the path',
             'example' => 'tracert google.com',
             'output' => 'List of hops showing latency at each router',
             'next' => 'If a hop shows "Request timed out" — connectivity issue at that point.'],
            ['id' => 8, 'command' => 'nslookup', 'category' => 'Network', 'risk' => 'safe',
             'description' => 'Query DNS servers for domain name resolution',
             'when' => 'When websites don\'t load but IP addresses work',
             'example' => 'nslookup google.com',
             'output' => 'Server: dns-server.local, Address: 192.168.1.1\nNon-authoritative answer: Name: google.com, Address: 142.250.xx.xx',
             'next' => 'If fails: DNS server issue. Try: nslookup google.com 8.8.8.8'],
            ['id' => 9, 'command' => 'sfc /scannow', 'category' => 'System', 'risk' => 'caution',
             'description' => 'Scan and repair corrupted Windows system files',
             'when' => 'System instability, BSOD, application crashes, missing DLL errors',
             'example' => 'Run as Admin: sfc /scannow',
             'output' => 'Windows Resource Protection found corrupt files and successfully repaired them',
             'next' => 'If errors remain: run DISM /Online /Cleanup-Image /RestoreHealth'],
            ['id' => 10, 'command' => 'DISM /Online /Cleanup-Image /RestoreHealth', 'category' => 'System', 'risk' => 'caution',
             'description' => 'Repair Windows system image using Windows Update',
             'when' => 'When sfc /scannow cannot fix all errors',
             'example' => 'DISM /Online /Cleanup-Image /RestoreHealth',
             'output' => 'The operation completed successfully',
             'next' => 'After DISM, run sfc /scannow again. May require internet.'],
            ['id' => 11, 'command' => 'chkdsk C: /f', 'category' => 'Disk', 'risk' => 'caution',
             'description' => 'Check and fix disk errors on the C: drive',
             'when' => 'Slow file access, disk errors in Event Viewer, 100% disk usage',
             'example' => 'Run as Admin: chkdsk C: /f',
             'output' => 'Scheduled to run on next restart. Type Y to confirm.',
             'next' => 'Restart computer. CHKDSK runs before Windows loads.'],
            ['id' => 12, 'command' => 'taskmgr', 'category' => 'Process', 'risk' => 'safe',
             'description' => 'Open Windows Task Manager',
             'when' => 'To check CPU, memory, disk usage; to end unresponsive processes; to manage startup programs',
             'example' => 'taskmgr  or  Ctrl+Shift+Esc',
             'output' => 'Task Manager window with processes, performance, and startup tabs',
             'next' => 'Check Processes tab for high usage. Check Startup tab to manage boot apps.'],
            ['id' => 13, 'command' => 'eventvwr', 'category' => 'System', 'risk' => 'safe',
             'description' => 'Open Windows Event Viewer',
             'when' => 'To investigate system errors, crashes, BSODs, and application failures',
             'example' => 'eventvwr',
             'output' => 'Event Viewer with System, Application, and Security logs',
             'next' => 'Check Windows Logs > System for Critical/Error events. Filter by date.'],
            ['id' => 14, 'command' => 'netstat -an', 'category' => 'Network', 'risk' => 'safe',
             'description' => 'Display all active network connections and listening ports',
             'when' => 'To verify which ports are open, check for suspicious connections, or debug network services',
             'example' => 'netstat -an',
             'output' => 'List of TCP/UDP connections with local/remote addresses and states',
             'next' => 'ESTABLISHED = active connection. LISTENING = waiting for connections.'],
            ['id' => 15, 'command' => 'systeminfo', 'category' => 'System', 'risk' => 'safe',
             'description' => 'Display comprehensive system information',
             'when' => 'To gather OS version, hardware specs, installed hotfixes, and network configuration',
             'example' => 'systeminfo',
             'output' => 'OS Name, Version, Processor, RAM, Network Cards, Hotfixes',
             'next' => 'Useful for documenting device specs. Check hotfixes for pending updates.'],
        ];
    }
    
    // ===== TOOLS =====
    public static function tools() {
        return [
            ['id' => 1, 'name' => 'Phillips Screwdriver Set', 'icon' => 'screwdriver', 'category' => 'Hand Tools',
             'purpose' => 'Opening computer cases, securing components',
             'when' => 'Hardware installation, RAM upgrade, SSD installation, opening panels',
             'safety' => 'Use correct size to avoid stripping screws'],
            ['id' => 2, 'name' => 'Anti-Static Wrist Strap', 'icon' => 'shield', 'category' => 'Safety',
             'purpose' => 'Prevent electrostatic discharge damage to components',
             'when' => 'Any time you touch internal computer components',
             'safety' => 'Always clip to a grounded metal surface'],
            ['id' => 3, 'name' => 'Network Cable Tester', 'icon' => 'zap', 'category' => 'Network',
             'purpose' => 'Test Ethernet cable continuity and correct wiring',
             'when' => 'Network connectivity issues, new cable installations',
             'safety' => 'Low voltage tool, safe for normal use'],
            ['id' => 4, 'name' => 'USB Boot Drive (8GB+)', 'icon' => 'usb', 'category' => 'Software',
             'purpose' => 'Boot Windows recovery, install OS, run diagnostic tools',
             'when' => 'OS repair, fresh install, virus scan from external boot',
             'safety' => 'Ensure drive contains correct images before use'],
            ['id' => 5, 'name' => 'Thermal Paste', 'icon' => 'thermometer', 'category' => 'Hardware',
             'purpose' => 'Replace thermal compound between CPU/GPU and heatsink',
             'when' => 'Overheating issues after heatsink removal',
             'safety' => 'Do not apply too much. Clean old paste with isopropyl alcohol.'],
            ['id' => 6, 'name' => 'Multimeter', 'icon' => 'activity', 'category' => 'Diagnostics',
             'purpose' => 'Measure voltage, current, resistance in electrical circuits',
             'when' => 'PSU testing, cable testing, outlet verification',
             'safety' => 'Use appropriate voltage range. Never measure current in-circuit.'],
            ['id' => 7, 'name' => 'Crimping Tool', 'icon' => 'scissors', 'category' => 'Network',
             'purpose' => 'Terminate Ethernet cables with RJ45 connectors',
             'when' => 'Creating custom-length network cables, replacing damaged connectors',
             'safety' => 'Use correct wiring standard (T568B)'],
            ['id' => 8, 'name' => 'Cable Labels and Tags', 'icon' => 'tag', 'category' => 'Organization',
             'purpose' => 'Label cables for easy identification',
             'when' => 'During installation or reorganization of network/server cables',
             'safety' => 'None — organizational tool'],
        ];
    }
    
    // ===== TIPS =====
    public static function tips() {
        return [
            ['id' => 1, 'category' => 'Hardware', 'text' => 'Before replacing a component, test the suspected component against a known-good component whenever practical.'],
            ['id' => 2, 'category' => 'Network', 'text' => 'Always ping the gateway first when troubleshooting network issues. If gateway ping fails, focus on local network before checking DNS.'],
            ['id' => 3, 'category' => 'Software', 'text' => 'Run sfc /scannow as a first step for many Windows issues. It is safe and can resolve corruption without data loss.'],
            ['id' => 4, 'category' => 'Safety', 'text' => 'Always wear an anti-static wrist strap when touching internal computer components. A single static discharge can destroy sensitive electronics.'],
            ['id' => 5, 'category' => 'Printer', 'text' => 'When a printer shows offline, always restart the Print Spooler service first. This resolves the issue in about 60% of cases.'],
            ['id' => 6, 'category' => 'Customer Communication', 'text' => 'Explain what you are doing in simple terms. "I am checking if the cable is connected properly" is better than "I am verifying the physical layer."'],
            ['id' => 7, 'category' => 'Troubleshooting', 'text' => 'Always start with the simplest possible cause. Check cables before checking hardware. Check software before replacing parts.'],
            ['id' => 8, 'category' => 'CCTV', 'text' => 'When a single camera goes offline, check the PoE switch port first. Move the cable to a known-good port before suspecting the camera.'],
        ];
    }
    
    // ===== TICKETS =====
    public static function tickets() {
        return [
            ['id' => 1001, 'title' => 'No Display — Desktop PC', 'device' => 'Dell OptiPlex 7090', 'department' => 'Finance',
             'location' => 'Floor 3, Desk 42', 'priority' => 'high', 'status' => 'solved', 'technician' => 'Juan D.',
             'created' => '2026-08-22 09:15:00', 'resolved' => '2026-08-22 10:30:00', 'category' => 'Display',
             'issue_id' => 1],
            ['id' => 1002, 'title' => 'Network Slow — Floor 3', 'device' => 'HP ProBook 450', 'department' => 'HR',
             'location' => 'Floor 3, Room 301', 'priority' => 'medium', 'status' => 'in_progress', 'technician' => 'Maria S.',
             'created' => '2026-08-22 11:00:00', 'resolved' => null, 'category' => 'Network',
             'issue_id' => 8],
            ['id' => 1003, 'title' => 'Printer Offline — Reception', 'device' => 'HP LaserJet Pro M404', 'department' => 'Reception',
             'location' => 'Ground Floor, Reception', 'priority' => 'high', 'status' => 'escalated', 'technician' => 'You',
             'created' => '2026-08-22 08:30:00', 'resolved' => null, 'category' => 'Printer',
             'issue_id' => 10],
            ['id' => 1004, 'title' => 'No Sound — Meeting Room', 'device' => 'Lenovo ThinkCentre M70s', 'department' => 'Operations',
             'location' => 'Floor 2, Meeting Room A', 'priority' => 'medium', 'status' => 'solved', 'technician' => 'Carlos R.',
             'created' => '2026-08-22 10:45:00', 'resolved' => '2026-08-22 11:20:00', 'category' => 'Sound',
             'issue_id' => 6],
            ['id' => 1005, 'title' => 'WiFi Not Connecting', 'device' => 'Dell Latitude 5520', 'department' => 'Sales',
             'location' => 'Floor 1, Sales Area', 'priority' => 'low', 'status' => 'in_progress', 'technician' => 'Ana T.',
             'created' => '2026-08-22 11:30:00', 'resolved' => null, 'category' => 'Network',
             'issue_id' => 9],
        ];
    }
    
    // ===== DEPARTMENTS =====
    public static function departments() {
        return [
            ['id' => 1, 'name' => 'Finance', 'head' => 'Maria Santos', 'email' => 'finance@company.local', 'users' => 24, 'location' => 'Floor 3'],
            ['id' => 2, 'name' => 'HR', 'head' => 'Ana Torres', 'email' => 'hr@company.local', 'users' => 15, 'location' => 'Floor 2'],
            ['id' => 3, 'name' => 'Operations', 'head' => 'Carlos Reyes', 'email' => 'ops@company.local', 'users' => 45, 'location' => 'Floor 1 & 2'],
            ['id' => 4, 'name' => 'Sales', 'head' => 'Rica Villanueva', 'email' => 'sales@company.local', 'users' => 32, 'location' => 'Floor 1'],
            ['id' => 5, 'name' => 'IT', 'head' => 'System Admin', 'email' => 'it@company.local', 'users' => 8, 'location' => 'Floor 3, IT Room'],
            ['id' => 6, 'name' => 'Reception', 'head' => 'Joy Mendoza', 'email' => 'reception@company.local', 'users' => 5, 'location' => 'Ground Floor'],
        ];
    }
    
    // ===== USERS =====
    public static function users() {
        return [
            ['id' => 1, 'name' => 'System Admin', 'email' => 'admin@fieldit.local', 'role' => 'Super Admin', 'department' => 'IT', 'status' => 'active', 'last_login' => '2026-08-22 12:00:00'],
            ['id' => 2, 'name' => 'Juan Dela Cruz', 'email' => 'fieldit@fieldit.local', 'role' => 'Field IT', 'department' => 'IT', 'status' => 'active', 'last_login' => '2026-08-22 09:30:00'],
            ['id' => 3, 'name' => 'Maria Santos', 'email' => 'supervisor@fieldit.local', 'role' => 'Supervisor', 'department' => 'Finance', 'status' => 'active', 'last_login' => '2026-08-22 08:00:00'],
            ['id' => 4, 'name' => 'Ana Torres', 'email' => 'user@fieldit.local', 'role' => 'Standard User', 'department' => 'HR', 'status' => 'active', 'last_login' => '2026-08-21 16:00:00'],
        ];
    }
    
    // ===== AUDIT LOGS =====
    public static function auditLogs() {
        return [
            ['id' => 1, 'user' => 'System Admin', 'action' => 'LOGIN', 'resource' => 'Session', 'ip' => '192.168.1.50', 'time' => '2026-08-22 12:00:00', 'details' => 'Successful login'],
            ['id' => 2, 'user' => 'Juan Dela Cruz', 'action' => 'CREATE', 'resource' => 'Ticket #1001', 'ip' => '192.168.1.51', 'time' => '2026-08-22 09:15:00', 'details' => 'Created troubleshooting ticket for No Display'],
            ['id' => 3, 'user' => 'Juan Dela Cruz', 'action' => 'EDIT', 'resource' => 'Ticket #1001', 'ip' => '192.168.1.51', 'time' => '2026-08-22 10:30:00', 'details' => 'Marked ticket as solved — reseated RAM module'],
            ['id' => 4, 'user' => 'Maria Santos', 'action' => 'APPROVE', 'resource' => 'Knowledge #3', 'ip' => '192.168.1.52', 'time' => '2026-08-22 08:45:00', 'details' => 'Approved article "Printer Offline Fix" for publication'],
            ['id' => 5, 'user' => 'System Admin', 'action' => 'CREATE', 'resource' => 'Department', 'ip' => '192.168.1.50', 'time' => '2026-08-21 14:00:00', 'details' => 'Created department "Reception"'],
            ['id' => 6, 'user' => 'System Admin', 'action' => 'EDIT', 'resource' => 'AI Settings', 'ip' => '192.168.1.50', 'time' => '2026-08-20 10:00:00', 'details' => 'Updated AI provider configuration to Ollama'],
        ];
    }
    
    // ===== AI RESPONSES =====
    public static function aiResponse($message) {
        $msg = strtolower($message);
        
        if (strpos($msg, 'no display') !== false || strpos($msg, 'no screen') !== false || strpos($msg, 'black screen') !== false) {
            return [
                'response' => "### Understanding the Problem\nYour computer has no display output. This could be caused by cable issues, monitor problems, GPU/RAM failures, or BIOS settings.\n\n### Most Likely Causes\n1. **Loose display cable** — Most common cause\n2. **Monitor set to wrong input** — Easy to fix\n3. **RAM not seated properly** — Common after moving the PC\n4. **GPU issue** — May need reseating or replacement\n\n### Start Here\n**Step 1:** Check if the computer is powered on (fans spinning, LEDs on)\n**Step 2:** Check the display cable connection on BOTH ends\n**Step 3:** Press the monitor input button to cycle through HDMI/DP/VGA\n\n### When to Escalate\nIf all cable checks pass and an external monitor also shows no display, escalate for hardware diagnosis.",
                'confidence' => 'high',
                'sources' => ['Company Knowledge Base', 'Field IT Experience'],
            ];
        }
        
        if (strpos($msg, 'no power') !== false || strpos($msg, 'not turning on') !== false || strpos($msg, 'dead') !== false) {
            return [
                'response' => "### Understanding the Problem\nThe device is not powering on at all. No LEDs, no fan spin, nothing.\n\n### Most Likely Causes\n1. **Outlet/power strip issue** — Test with another device\n2. **Loose power cable** — Check both ends\n3. **PSU switch off** — Desktop PSU rocker switch\n4. **Faulty PSU** — May need replacement\n\n### Start Here\n**Step 1:** Test the wall outlet with a phone charger\n**Step 2:** Check power strip/UPS is ON\n**Step 3:** Verify PSU switch is in ON (I) position\n**Step 4:** For laptops: try a known-good charger\n\n### When to Escalate\nIf no power at all after testing outlet, cable, and PSU, escalate for hardware diagnosis.",
                'confidence' => 'high',
                'sources' => ['Company Knowledge Base'],
            ];
        }
        
        if (strpos($msg, 'no internet') !== false || strpos($msg, 'no network') !== false || strpos($msg, 'can') !== false && strpos($msg, 'browse') !== false) {
            return [
                'response' => "### Understanding the Problem\nNetwork connectivity issue — cannot access the internet.\n\n### Most Likely Causes\n1. **Cable/WiFi disconnected** — Physical layer\n2. **DHCP failure** — No IP address assigned\n3. **DNS issue** — IP works but names don't resolve\n4. **Gateway/router issue** — Network infrastructure problem\n\n### Start Here\n**Step 1:** Open CMD, run `ipconfig` — check for valid IP\n**Step 2:** If no IP (169.254.x.x) → run `ipconfig /release` then `/renew`\n**Step 3:** If IP OK → `ping 8.8.8.8` (test internet by IP)\n**Step 4:** If ping works → `ipconfig /flushdns` (DNS issue)\n\n### When to Escalate\nIf multiple computers are affected, escalate to network team.",
                'confidence' => 'high',
                'sources' => ['Company Knowledge Base'],
            ];
        }
        
        // Default IT response
        return [
            'response' => "### Understanding the Problem\nI understand you're experiencing: *\"{$message}\"*\n\n### Diagnostic Questions\nTo help you better, please answer:\n1. What device is affected? (Laptop/Desktop/Printer/Other)\n2. When did this start?\n3. Were any changes made recently?\n4. Is this affecting other users?\n\n### General Steps\n**Step 1:** Document the symptoms precisely\n**Step 2:** Check for recent changes (updates, moves, new software)\n**Step 3:** Test on a known-good device if possible\n**Step 4:** Check the Knowledge Base for similar issues\n\n### When to Escalate\nIf the issue persists after basic checks, create a troubleshooting ticket with full details.",
            'confidence' => 'medium',
            'sources' => ['General IT Knowledge'],
        ];
    }
    
    // ===== STATISTICS =====
    public static function stats() {
        return [
            'total_sessions' => 127,
            'solved_today' => 8,
            'pending_tickets' => 5,
            'kb_articles' => 342,
            'sessions_trend' => '+12',
            'solved_trend' => '+3',
            'pending_trend' => '-2',
            'articles_trend' => '+5',
            'avg_resolution_time' => '45 min',
            'solve_rate' => 89,
            'escalation_rate' => 11,
            'top_issues' => [
                ['name' => 'No Display', 'count' => 18, 'pct' => 35],
                ['name' => 'Printer Offline', 'count' => 14, 'pct' => 27],
                ['name' => 'Network Connectivity', 'count' => 11, 'pct' => 21],
                ['name' => 'Application Crash', 'count' => 9, 'pct' => 17],
                ['name' => 'Slow Performance', 'count' => 7, 'pct' => 14],
            ],
            'weekly_data' => [
                ['day' => 'Mon', 'solved' => 12, 'escalated' => 2],
                ['day' => 'Tue', 'solved' => 15, 'escalated' => 1],
                ['day' => 'Wed', 'solved' => 10, 'escalated' => 3],
                ['day' => 'Thu', 'solved' => 18, 'escalated' => 2],
                ['day' => 'Fri', 'solved' => 8, 'escalated' => 1],
            ],
        ];
    }
    
    // ===== NOTIFICATIONS =====
    public static function notifications() {
        return [
            ['id' => 1, 'type' => 'ticket', 'title' => 'New Ticket Assigned', 'message' => 'Ticket #1005 WiFi Not Connecting assigned to you', 'time' => '5 min ago', 'read' => false],
            ['id' => 2, 'type' => 'escalation', 'title' => 'Ticket Escalated', 'message' => 'Printer Offline ticket #1003 escalated to supervisor', 'time' => '1 hour ago', 'read' => false],
            ['id' => 3, 'type' => 'kb', 'title' => 'Article Updated', 'message' => 'BSOD Guide updated by Juan Dela Cruz', 'time' => '2 hours ago', 'read' => true],
            ['id' => 4, 'type' => 'system', 'title' => 'System Maintenance', 'message' => 'Scheduled maintenance on Sunday 2AM-4AM', 'time' => '1 day ago', 'read' => true],
        ];
    }
}
